// Each row keeps English, Portuguese and Dutch together. Deeper cells remain
// on demand: these are knowledge records, not extra animated scene objects.
const row=(id,parentId,title,body,options={})=>({id,parentId,title,body,...options});
const roots=[
 row('food-forest',null,['Food Forest','Floresta alimentar','Voedselbos'],['Explore a native rainforest layer within the food forest. Follow this plant into its forest setting, role in nature and wildlife relationships.','Explore um estrato nativo dentro da floresta alimentar. Siga a planta até ao seu ambiente florestal, papel na natureza e relações com a fauna.','Ontdek een inheemse regenwoudlaag in het voedselbos. Volg deze plant naar haar bosomgeving, rol in de natuur en relaties met dieren.'],{type:'category',art:'wildlife'}),
 row('uses',null,['Uses','Usos','Gebruik'],['Explore what this plant offers people and the living landscape. Separate documented uses from activities and design ideas you can investigate here.','Explore o que esta planta oferece às pessoas e à paisagem viva. Separe usos documentados de atividades e ideias a investigar aqui.','Ontdek wat deze plant mensen en het levende landschap biedt. Onderscheid beschreven toepassingen van activiteiten en ontwerpideeën voor deze plek.'],{type:'category',art:'identity'}),
 row('propagation',null,['Propagation','Propagação','Vermeerdering'],['Follow seeds, cuttings and parent-plant records. Open the species-specific route and keep source, method and outcome together.','Siga sementes, estacas e registos da planta-mãe. Abra o percurso desta espécie e mantenha origem, método e resultado juntos.','Volg zaden, stekken en moederplantgegevens. Open de soortspecifieke route en bewaar herkomst, methode en resultaat samen.'],{type:'category',art:'seed'}),
 row('scientific-information',null,['Scientific Information','Informação científica','Wetenschappelijke informatie'],['Check the name and the structures that distinguish this plant. Compare the living specimen with botanical descriptions; illustrations help explain features but do not prove an identification.','Confirme o nome e as estruturas distintivas. Compare o exemplar com descrições botânicas; as ilustrações ajudam a explicar, mas não provam uma identificação.','Controleer naam en onderscheidende structuren. Vergelijk de echte plant met botanische beschrijvingen; illustraties helpen uitleggen maar bewijzen geen determinatie.'],{type:'category',art:'identity'}),
 row('historical-data',null,['Historical Data','Dados históricos','Historische gegevens'],['Connect published sources with the history of this particular plant. Keep planting, provenance and observations dated, and distinguish local records from species-wide claims.','Ligue fontes publicadas à história desta planta. Date plantação, origem e observações, distinguindo registos locais de afirmações sobre toda a espécie.','Verbind gepubliceerde bronnen met de geschiedenis van deze plant. Dateer aanplant, herkomst en waarnemingen en onderscheid lokale dossiers van soortbrede uitspraken.'],{type:'category',art:'identity'}),
 row('cultivation',null,['Cultivation','Cultivo','Teelt'],['Use habitat and growing guidance to investigate a suitable position. Follow light, moisture, shelter and mature size over time instead of treating a native label as a planting guarantee.','Use habitat e orientações de cultivo para investigar um lugar adequado. Acompanhe luz, humidade, abrigo e tamanho adulto; ser nativa não garante sucesso.','Gebruik habitat en teeltadvies om een geschikte plek te onderzoeken. Volg licht, vocht, beschutting en volwassen grootte; een inheemse naam garandeert geen succes.'],{type:'category',art:'wildlife'})
];
const shared=[
 row('role-in-nature','native-forest-within-food-forest',
 ['Role in nature','Papel na natureza','Rol in de natuur'],
 ['Follow this plant beyond its harvest: its forest layer, the animals using it, and what happens to leaves, flowers and seeds. Open a relationship, then look for evidence in your own place.','Siga esta planta para além da colheita: o seu estrato florestal, os animais que a usam e o destino de folhas, flores e sementes. Abra uma relação e procure provas no seu lugar.','Volg deze plant voorbij de oogst: haar boslaag, dieren die haar gebruiken en wat er met bladeren, bloemen en zaden gebeurt. Open een relatie en zoek bewijs op je eigen plek.'],{type:'category',art:'wildlife'}),
 row('forest-layers','role-in-nature',
 ['One plant, several forest layers','Uma planta, vários estratos','Eén plant, meerdere boslagen'],
 ['Design idea: connect this plant with a taller canopy, nearby shrubs and ground cover. Compare sun and shelter at each height. A layered planting is a community to observe; adding one native alone does not recreate a rainforest.','Ideia de desenho: ligue esta planta a um dossel mais alto, arbustos próximos e cobertura do solo. Compare sol e abrigo a cada altura. Uma plantação estratificada é uma comunidade a observar; uma só planta nativa não recria uma floresta tropical.','Ontwerpidee: verbind deze plant met een hogere kroonlaag, struiken en bodembedekking. Vergelijk zon en beschutting op elke hoogte. Een gelaagde beplanting is een gemeenschap om te volgen; één inheemse plant maakt nog geen regenwoud.'],{type:'activity',evidence:'local_observation'}),
 row('leaf-litter-observation','forest-layers',
 ['From leaf to forest floor','Da folha ao solo da floresta','Van blad naar bosbodem'],
 ['Compare fallen leaves beneath this plant with a nearby bare patch. Record moisture, leaf breakdown and visible decomposers without disturbing them. This is a local investigation of litter cycling, not a measured soil-improvement claim for this species.','Compare folhas caídas sob esta planta com uma zona próxima sem cobertura. Registe humidade, decomposição e decompositores visíveis sem os perturbar. É uma investigação local, não uma afirmação medida de melhoria do solo por esta espécie.','Vergelijk gevallen bladeren onder deze plant met een kale plek ernaast. Noteer vocht, afbraak en zichtbare afbrekers zonder verstoring. Dit is lokaal onderzoek naar strooisel, geen gemeten claim over bodemverbetering door deze soort.'],{type:'activity',evidence:'local_observation'}),
 row('wildlife-relationships','role-in-nature',
 ['Wildlife relationships','Relações com a fauna','Relaties met dieren'],
 ['A visitor may feed, shelter, lay eggs or move seeds. Those are different relationships. Follow this plant’s documented examples below; use an observation Note for visitors whose role or identity is still uncertain.','Um visitante pode alimentar-se, abrigar-se, pôr ovos ou transportar sementes. São relações diferentes. Siga os exemplos documentados desta planta; use uma Nota para visitantes cuja função ou identidade ainda seja incerta.','Een bezoeker kan eten, schuilen, eieren leggen of zaden verspreiden. Dat zijn verschillende relaties. Volg de gedocumenteerde voorbeelden van deze plant; gebruik een observatienotitie wanneer rol of identiteit onzeker is.'],{type:'category',art:'wildlife'}),
 row('wildlife-field-watch','wildlife-relationships',
 ['Watch a relationship unfold','Observe uma relação a acontecer','Volg een relatie in actie'],
 ['Watch quietly for ten minutes. Record date, weather, plant stage, visitor and behaviour. A flower visit alone does not prove pollination; a missing fruit does not identify its eater. Repeated observations make the story stronger.','Observe em silêncio durante dez minutos. Registe data, tempo, fase da planta, visitante e comportamento. Uma visita à flor não prova polinização; um fruto desaparecido não identifica quem o comeu. Observações repetidas reforçam a história.','Kijk tien minuten rustig toe. Noteer datum, weer, plantstadium, bezoeker en gedrag. Een bloembezoek bewijst geen bestuiving; verdwenen fruit onthult niet wie het at. Herhaalde waarnemingen versterken het verhaal.'],{type:'activity',evidence:'local_observation'}),
 row('forest-teaching-plant','uses',
 ['A living outdoor lesson','Uma aula viva ao ar livre','Een levende buitenles'],
 ['Choose one question from this PIMO and connect it to the actual plant. Learners can compare leaves, follow a visitor or map seed movement. Add dated evidence to the Orb so the next visitor can continue the investigation.','Escolha uma pergunta deste PIMO e ligue-a à planta real. Os alunos podem comparar folhas, seguir um visitante ou mapear sementes. Acrescente provas datadas ao Orbe para o próximo visitante continuar a investigação.','Kies een vraag uit deze PIMO en verbind haar met de echte plant. Leerlingen kunnen bladeren vergelijken, een bezoeker volgen of zaadverplaatsing in kaart brengen. Voeg gedateerd bewijs toe aan de Orb voor de volgende onderzoeker.'],{type:'activity',evidence:'local_observation'}),
 row('propagation-provenance','propagation',
 ['Keep the parent plant in the record','Registe a planta-mãe','Bewaar de moederplant in het dossier'],
 ['Record the parent plant, seed or cutting source, collection date and method. Keep cultivated selections separate from wild-origin material. This creates a traceable propagation story instead of assuming every seedling will match the parent.','Registe a planta-mãe, origem da semente ou estaca, data e método. Separe seleções cultivadas de material silvestre. Assim a propagação fica rastreável, sem supor que toda a plântula será igual à mãe.','Noteer moederplant, herkomst van zaad of stek, datum en methode. Houd gekweekte selecties apart van materiaal met wilde herkomst. Zo wordt vermeerdering traceerbaar zonder aan te nemen dat iedere zaailing op de ouder lijkt.'],{type:'activity',evidence:'local_observation',art:'seed'}),
 row('leaf-comparison','scientific-information',
 ['Read the leaf before naming it','Leia a folha antes de a nomear','Lees het blad vóór de naam'],
 ['Compare several mature leaves: arrangement, size, margin, veins and attachment to the twig. Use the illustration as a teaching aid, then check the botanical source and the real specimen. A generated picture is not identification evidence.','Compare várias folhas adultas: disposição, tamanho, margem, nervuras e ligação ao ramo. Use a ilustração para aprender e confirme na fonte botânica e no exemplar real. Uma imagem gerada não é prova de identificação.','Vergelijk meerdere volwassen bladeren: stand, grootte, rand, nerven en aanhechting. Gebruik de illustratie als leermiddel en controleer de botanische bron en echte plant. Een gegenereerde afbeelding is geen determinatiebewijs.'],{type:'activity',evidence:'local_observation',art:'identity'}),
 row('local-history-record','historical-data',
 ['Begin this plant’s local history','Comece a história local desta planta','Begin de lokale geschiedenis'],
 ['Who planted it, when and from what source? Add planting photos, earlier names and dated observations. Distinguish this site’s records from published species history; leave unknown details open rather than inventing an origin story.','Quem a plantou, quando e de que origem? Acrescente fotos, nomes anteriores e observações datadas. Separe os registos do lugar da história publicada da espécie; deixe lacunas em aberto em vez de inventar uma origem.','Wie plantte haar, wanneer en met welke herkomst? Voeg plantfoto’s, eerdere namen en gedateerde waarnemingen toe. Scheid lokale dossiers van gepubliceerde soortgeschiedenis; laat onbekende details open in plaats van een oorsprongsverhaal te verzinnen.'],{type:'activity',evidence:'local_observation'}),
 row('site-fit-observation','cultivation',
 ['Test the fit of this place','Avalie este lugar','Onderzoek deze plek'],
 ['Compare the species’ published habitat with your site’s light, drainage, shelter and seasonal moisture. Mark a candidate position before planting. Return with a Note after rain and during a dry spell: a habitat clue is a starting point, not a guarantee.','Compare o habitat publicado com a luz, drenagem, abrigo e humidade sazonal do lugar. Marque uma posição antes de plantar. Volte após chuva e numa fase seca: uma pista de habitat é um começo, não uma garantia.','Vergelijk het beschreven leefgebied met licht, afwatering, beschutting en seizoensvocht op je locatie. Markeer een plek vóór het planten. Kom terug na regen en tijdens droogte: habitat is een aanwijzing, geen garantie.'],{type:'activity',evidence:'local_observation'}),
 row('published-and-local-history','historical-data',
 ['A source and a site tell different histories','Uma fonte e um lugar têm histórias distintas','Bron en locatie vertellen verschillende geschiedenissen'],
 ['Open the botanical source to see the published species record. Keep its author and date separate from your planting history. Later observations can extend this PIMO without rewriting the source or presenting personal observations as established species facts.','Abra a fonte botânica para ver o registo publicado. Separe autor e data da história da sua plantação. Observações posteriores podem ampliar este PIMO sem alterar a fonte nem apresentar observações pessoais como factos da espécie.','Open de botanische bron voor het gepubliceerde soortdossier. Houd auteur en datum apart van je aanplantgeschiedenis. Latere waarnemingen kunnen deze PIMO uitbreiden zonder de bron te herschrijven of persoonlijke waarnemingen als soortfeiten te presenteren.'],{type:'activity',evidence:'local_observation'})
];
const specific={
 'blue-quandong':[
 row('canopy-recovery','role-in-nature',
 ['Helping a canopy return','Ajudar o dossel a regressar','Een kroonlaag laten terugkeren'],
 ['Rainforest Rescue uses Blue Quandong in restoration for its fast growth and canopy closure. Its reported growth reflects particular revegetation sites. Follow canopy development over time rather than promising the same growth rate in every garden.','A Rainforest Rescue usa quandong-azul na restauração pelo crescimento rápido e fecho do dossel. Os resultados referem-se a locais específicos. Acompanhe o dossel no tempo, sem prometer a mesma velocidade em todos os jardins.','Rainforest Rescue gebruikt blauwe quandong bij herstel vanwege snelle groei en kroonsluiting. De beschreven groei geldt voor bepaalde herstelplekken. Volg kroonontwikkeling in de tijd zonder dezelfde snelheid voor iedere tuin te beloven.'],{source:'rainforest-rescue-blue-quandong',art:'wildlife'}),
 row('water-seed-journey','wildlife-relationships',
 ['Animals and water move the story','Animais e água levam a história','Dieren en water dragen het verhaal'],
 ['Rainforest Rescue records stones in cassowary droppings and describes nuts transported along watercourses, sometimes reaching beaches. Compare animal dispersal with water transport: one plant can have more than one route away from its parent.','A Rainforest Rescue regista caroços em fezes de casuar e descreve transporte por cursos de água, por vezes até às praias. Compare dispersão animal e transporte pela água: uma planta pode ter várias rotas para longe da mãe.','Rainforest Rescue beschrijft pitten in kasuariskeutels en transport via waterlopen, soms tot stranden. Vergelijk verspreiding door dieren met watertransport: een plant kan meerdere routes van de moederboom vandaan hebben.'],{source:'rainforest-rescue-blue-quandong',art:'seed'}),
 row('regional-fruit-watch','wildlife-relationships',
 ['Which fruit visitors live here?','Que visitantes vivem aqui?','Welke fruitbezoekers leven hier?'],
 ['Cassowaries belong to northern rainforest regions, not every Blue Quandong planting. At your site, record birds taking fruit in the crown and animals using fallen fruit. Match each identification to local range before attaching a wildlife claim.','Os casuares vivem em regiões florestais do norte, não junto de toda a plantação de quandong. Registe aves na copa e animais nos frutos caídos. Confirme a distribuição local antes de atribuir uma relação.','Kasuarissen horen bij noordelijke regenwoudgebieden, niet iedere quandongaanplant. Noteer vogels die fruit uit de kroon halen en dieren bij gevallen fruit. Controleer lokale verspreiding voordat je een relatie vastlegt.'],{type:'activity',evidence:'local_observation',source:'rainforest-rescue-blue-quandong',art:'wildlife'}),
 row('stone-seed-difference','blue-quandong-stone',
 ['A stone can hold several seeds','Um caroço pode conter várias sementes','Een pit kan meerdere zaden bevatten'],
 ['The sculptured stone is not a single exposed seed. Rainforest Rescue notes several seeds inside each nut. Follow collection, sowing and emergence as separate records; several possible seedlings do not guarantee successful germination.','O caroço esculpido não é uma única semente exposta. A Rainforest Rescue refere várias sementes em cada caroço. Registe recolha, sementeira e emergência separadamente; várias sementes não garantem germinação.','De gegroefde pit is niet één bloot zaad. Rainforest Rescue noemt meerdere zaden per pit. Houd verzamelen, zaaien en opkomst afzonderlijk bij; meerdere mogelijke zaailingen garanderen geen kieming.'],{source:'rainforest-rescue-blue-quandong',art:'seed'}),
 row('blue-quandong-space','cultivation',
 ['Plan for the tree, not today’s pot','Planeie a árvore, não o vaso','Plan voor de boom, niet de pot'],
 ['PlantNET describes a large rainforest tree, sometimes with buttressed roots. Leave room for its mature crown, roots and access. Use a site plan to compare future shade with paths and smaller plants before choosing its position.','A PlantNET descreve uma árvore florestal grande, por vezes com raízes tabulares. Reserve espaço para copa, raízes e acesso. Compare a sombra futura com caminhos e plantas menores antes de escolher o lugar.','PlantNET beschrijft een grote regenwoudboom, soms met plankwortels. Geef volwassen kroon, wortels en toegang ruimte. Vergelijk toekomstige schaduw met paden en kleinere planten voordat je de plek kiest.'],{source:'plantnet-blue-quandong'}),
 row('restoration-use','uses',
 ['A restoration and learning tree','Uma árvore de restauração e aprendizagem','Een herstel- en leerboom'],
 ['This example focuses on restoring forest structure and exploring fruit dispersal. Link the tree to restoration records and seed observations, rather than presenting every fruiting native as a ready-to-harvest orchard crop.','Este exemplo centra-se na estrutura florestal e dispersão de frutos. Ligue a árvore a registos de restauração e sementes, sem apresentar toda a nativa frutífera como cultura pronta a colher.','Dit voorbeeld richt zich op bosstructuur en zaadverspreiding. Verbind de boom met hersteldossiers en zaadwaarnemingen in plaats van iedere vruchtdragende inheemse plant als oogstklare teelt te presenteren.'],{source:'rainforest-rescue-blue-quandong'})
 ],
 'finger-lime':[
 row('butterfly-host-life','wildlife-relationships',
 ['A butterfly needs more than flowers','Uma borboleta precisa de mais que flores','Een vlinder heeft meer dan bloemen nodig'],
 ['Sunshine Coast Council lists Finger Lime as a host for the Dainty Swallowtail, Papilio anactus. Host foliage supports the caterpillar stage. A nectar garden and a caterpillar-host planting meet different needs in the butterfly’s life cycle.','A Câmara de Sunshine Coast indica a lima-caviar como hospedeira de Papilio anactus. A folhagem alimenta a fase de lagarta. Flores com néctar e plantas hospedeiras respondem a necessidades distintas no ciclo da borboleta.','Sunshine Coast Council noemt vingerlimoen als waardplant voor Papilio anactus. De bladeren ondersteunen het rupsenstadium. Nectarplanten en waardplanten vervullen verschillende behoeften in de levenscyclus.'],{source:'sunshine-coast-finger-lime-butterfly',art:'wildlife'}),
 row('host-leaf-observation','butterfly-host-life',
 ['Follow eggs, feeding and emergence','Siga ovos, alimentação e emergência','Volg eieren, vraat en uitkomen'],
 ['Record eggs or caterpillars only when you can identify them. Photograph the same twig over time without handling the insect. Note leaf loss and recovery; check what is present before pruning or treating the plant.','Registe ovos ou lagartas apenas quando os conseguir identificar. Fotografe o mesmo ramo no tempo, sem tocar no inseto. Anote perda de folhas e recuperação; verifique o que existe antes de podar ou tratar.','Registreer eieren of rupsen alleen als je ze kunt herkennen. Fotografeer dezelfde tak door de tijd zonder het insect aan te raken. Noteer bladverlies en herstel; kijk wat aanwezig is vóór snoeien of behandelen.'],{type:'activity',evidence:'local_observation',source:'sunshine-coast-finger-lime-butterfly',art:'wildlife'}),
 row('finger-lime-shelter','role-in-nature',
 ['A thorny understorey layer','Um sub-bosque espinhoso','Een doornige onderlaag'],
 ['ANBG describes a spiny shrub or small tree from rainforest communities. Its branching form gives your design a distinct lower woody layer. Investigate shelter use locally; thorns alone do not prove a particular bird nests here.','O ANBG descreve um arbusto ou pequena árvore espinhosa de comunidades florestais. A ramificação acrescenta um estrato lenhoso inferior. Investigue o uso como abrigo; espinhos não provam que determinada ave nidifica aqui.','ANBG beschrijft een stekelige struik of kleine boom uit regenwoudgemeenschappen. De vertakking vormt een eigen lagere houtige laag. Onderzoek lokaal gebruik als beschutting; doornen bewijzen geen nestgebruik door een bepaalde vogel.'],{source:'anbg-finger-lime'}),
 row('fruit-vesicles-use','uses',
 ['Explore the fruit’s tiny vesicles','Explore as pequenas vesículas','Ontdek de kleine sapblaasjes'],
 ['The cylindrical citrus fruit contains separate juice vesicles used for their tangy flavour and texture. Compare skin and pulp colour between named selections. Keep cultivar identity with a harvest record rather than treating all Finger Limes as identical.','O fruto cilíndrico contém vesículas de sumo apreciadas pelo sabor ácido e textura. Compare cor da casca e polpa entre seleções. Registe a cultivar com a colheita em vez de tratar todas as limas-caviar como iguais.','De cilindrische citrusvrucht bevat aparte sapblaasjes met een frisse zure smaak en textuur. Vergelijk schil- en pulpkleur tussen selecties. Bewaar cultivaridentiteit bij oogstgegevens in plaats van alle vingerlimoenen gelijk te behandelen.'],{source:'anbg-finger-lime',art:'identity'}),
 row('finger-lime-seedling-time','finger-lime-seed',
 ['Seedling and grafted are different stories','Plântula e enxerto têm histórias diferentes','Zaailing en ent zijn verschillende verhalen'],
 ['ANBG describes slow seedling growth and faster maturity in grafted plants. Record the propagation method and rootstock when known. A demo should show the distinction without promising a fixed fruiting date for every seedling or graft.','O ANBG descreve crescimento lento das plântulas e maturação mais rápida de plantas enxertadas. Registe método e porta-enxerto quando conhecidos. Distinga os percursos sem prometer uma data fixa de frutificação.','ANBG beschrijft langzame groei van zaailingen en snellere volwassenheid bij geënte planten. Noteer methode en onderstam indien bekend. Toon het verschil zonder iedere zaailing of ent een vaste vruchtzettingsdatum te beloven.'],{source:'anbg-finger-lime',art:'seed'}),
 row('finger-lime-growing-site','cultivation',
 ['Shelter, moisture and a way past the spines','Abrigo, humidade e espaço para espinhos','Beschutting, vocht en ruimte langs doornen'],
 ['ANBG recommends organic-rich soil and attention to summer moisture. Place spiny branches clear of access routes and plan room to observe or harvest. Compare the garden’s growing conditions with the cultivar and rootstock information supplied with the plant.','O ANBG recomenda solo rico em matéria orgânica e atenção à humidade de verão. Afaste ramos espinhosos dos acessos e reserve espaço para observar ou colher. Compare as condições com dados da cultivar e porta-enxerto.','ANBG adviseert organisch rijke grond en aandacht voor zomervocht. Houd stekelige takken buiten looproutes en laat ruimte voor observatie en oogst. Vergelijk omstandigheden met informatie over cultivar en onderstam.'],{source:'anbg-finger-lime'})
 ],
 'lemon-myrtle':[
 row('flower-event','role-in-nature',
 ['A flowering event in the woody layer','Uma floração no estrato lenhoso','Een bloeimoment in de houtige laag'],
 ['Lemon Myrtle produces clusters of small white flowers with conspicuous stamens. Its flowering creates an opportunity to compare visitor activity with nearby plants. Track your site’s season instead of assuming every region flowers on the same calendar.','A murta-limão produz grupos de pequenas flores brancas com estames evidentes. A floração permite comparar visitantes com plantas próximas. Acompanhe a estação local, sem supor um calendário igual para todas as regiões.','Citroenmirte vormt trossen kleine witte bloemen met opvallende meeldraden. De bloei biedt een kans om bezoekers met naburige planten te vergelijken. Volg het lokale seizoen zonder overal hetzelfde bloeikalender aan te nemen.'],{source:'anbg-lemon-myrtle',art:'wildlife'}),
 row('lemon-myrtle-visitors','wildlife-relationships',
 ['Who works among the stamens?','Quem visita os estames?','Wie bezoekt de meeldraden?'],
 ['Look for bees, flies and other insects visiting flowers, but label them as visitors until identified. Record contact with stamens and movement between flowers. The illustration suggests a field question; it does not establish a specific pollinator relationship.','Procure abelhas, moscas e outros insetos nas flores, mas registe-os como visitantes até serem identificados. Anote contacto com estames e movimento entre flores. A ilustração propõe uma pergunta, não prova um polinizador específico.','Zoek bijen, vliegen en andere bloembezoekers, maar noem ze bezoekers tot ze herkend zijn. Noteer contact met meeldraden en verplaatsing tussen bloemen. De illustratie stelt een veldvraag en bewijst geen specifieke bestuiversrelatie.'],{type:'activity',evidence:'local_observation',source:'anbg-lemon-myrtle',art:'wildlife'}),
 row('flower-to-capsule','lemon-myrtle-visitors',
 ['From flower visit to seed capsule','Da visita floral à cápsula','Van bloembezoek naar zaadcapsule'],
 ['Return to a marked flowering branch and follow capsule formation. Compare visitor notes with later fruit development. This can generate a useful question, but observations alone do not isolate which visitor caused seed formation.','Volte a um ramo florido marcado e acompanhe as cápsulas. Compare notas de visitantes com o desenvolvimento posterior. Surge uma pergunta útil, mas a observação isolada não determina que visitante causou a formação de sementes.','Volg capsulevorming aan een gemarkeerde bloeiende tak. Vergelijk bezoekersnotities met latere vruchtontwikkeling. Dit levert een onderzoeksvraag op, maar waarnemingen alleen bepalen niet welke bezoeker zaadvorming veroorzaakte.'],{type:'activity',evidence:'local_observation',source:'anbg-lemon-myrtle',art:'seed'}),
 row('aromatic-leaf-use','uses',
 ['Explore the aromatic leaf','Explore a folha aromática','Ontdek het aromatische blad'],
 ['ANBG describes strongly lemon-scented foliage. Compare leaf shape and scent as separate observations. The name “Lemon Myrtle” describes an aromatic rainforest plant, not a citrus fruit tree; keep its myrtle-family identity visible.','O ANBG descreve folhagem com forte aroma a limão. Compare forma e aroma como observações distintas. Murta-limão é uma planta aromática da floresta tropical, não uma árvore de citrinos; mantenha visível a família das mirtáceas.','ANBG beschrijft sterk naar citroen geurende bladeren. Vergelijk bladvorm en geur als aparte waarnemingen. Citroenmirte is een aromatische regenwoudplant, geen citrusfruitboom; houd de mirtefamilie zichtbaar.'],{source:'anbg-lemon-myrtle',art:'identity'}),
 row('lemon-myrtle-cuttings','propagation',
 ['A cutting keeps a plant connection','Uma estaca mantém a ligação','Een stek bewaart de verbinding'],
 ['ANBG describes tip cuttings and branches rooting where they touch the ground. Keep the parent identity and method with each new plant. Compare these routes with the tiny seeds held inside capsules rather than presenting all propagation as one process.','O ANBG descreve estacas apicais e ramos que enraízam ao tocar no solo. Registe a identidade da mãe e o método em cada nova planta. Compare esses percursos com as pequenas sementes das cápsulas.','ANBG beschrijft topstekken en takken die wortelen waar ze de grond raken. Bewaar ouderidentiteit en methode bij iedere nieuwe plant. Vergelijk deze routes met de kleine zaden in capsules in plaats van één universeel proces te tonen.'],{source:'anbg-lemon-myrtle',art:'seed'}),
 row('lemon-myrtle-sheltered-site','cultivation',
 ['Build a sheltered growing position','Crie um lugar de crescimento abrigado','Maak een beschutte groeiplek'],
 ['ANBG’s Rainforest Gully specimens benefit from canopy and surrounding shrubs. Its guidance favours rich, moist, mulched soil and shelter for young plants in frosty areas. Translate those clues into a site plan, then record how the plant responds.','Os exemplares no Rainforest Gully do ANBG beneficiam de dossel e arbustos. A orientação favorece solo rico, húmido, coberto e abrigo para jovens plantas em zonas de geada. Use essas pistas no plano e registe a resposta.','De planten in ANBG’s Rainforest Gully profiteren van kroonlaag en struiken. Het advies noemt rijke, vochtige, gemulchte grond en bescherming van jonge planten bij vorst. Vertaal die aanwijzingen naar een plan en volg de reactie.'],{source:'anbg-lemon-myrtle'})
 ]
};

const rowsFor=id=>[...roots,...shared,...(specific[id] || [])];
export function nativePlantDepthNodes(plant){
 return rowsFor(plant.id).map(item=>({id:item.id,parentId:item.parentId,title:item.title[0],preview:item.body[0],body:item.body[0],informationType:item.type || 'fact',evidenceStatus:item.evidence || 'sourced',status:'published',sourceIds:[item.source || plant.source.id],media:item.art?[{id:`${plant.id}-depth-${item.art}`,image:item.art==='identity'?plant.image:item.art==='seed'?plant.seedImage:plant.wildlifeImage,alt:`${plant.name} · ${item.title[0]}`,caption:item.art==='identity'?'Colour demo illustration':'Stylised black-and-white teaching illustration',kind:'illustration'}]:[]}));
}
export const NATIVE_PLANT_DEPTH_TRANSLATIONS=Object.freeze([...roots,...shared,...Object.values(specific).flat()].flatMap(item=>[item.title,item.body]));
