import {NOTE_TYPES,spatialNote,DYNAMIC_NOTE_STARTERS,noteStarter,validateSpatialNote} from './spatialNotes.js';
import {createNoteWidget,noteWidgetLibrary,noteWidgetDefinition,escapeNote as e,WIDGET_LIMIT} from './noteWidgets.js';
const timerEditorFields=item=>item.configuration?.actionTag
    ?`<label>Action<input data-widget-config="action" value="${e(item.configuration.action)}" placeholder="Fruit harvest / Scion ready"></label><label>Return after (days)<input type="number" min="0" max="3650" step="1" data-widget-days value="${Math.max(0,Math.round(Number(item.configuration.seconds ?? 864000)/86400))}"></label><small>Use the day/week spinner on the widget to choose your return date.</small>`
    :`<label>Countdown (minutes)<input type="number" min="1" data-widget-minutes value="${Math.max(1,(Number(item.configuration?.seconds)||240)/60)}"></label>`;
export function mountNoteWidgetEditor(root,marker,{onStarter=()=>{}}={}) {
    let draft=spatialNote(marker),libraryOpen=false;
    const render=()=>{
        root.innerHTML=`<legend>Note experience</legend><div class="note-type-library">${NOTE_TYPES.map(type=>`<button type="button" data-note-type="${type.id}" aria-pressed="${draft.type===type.id}"><span class="note-type-preview is-${type.id}"><i>Main Note</i>${type.id==='interactive'?'<b>Complete → ✓</b>':type.id==='dynamic'?'<b>Image</b><b>Timer</b><b>Checklist</b>':''}</span><strong>${type.label}</strong><small>${type.description}</small></button>`).join('')}</div>${draft.type==='interactive'?`<label>Action label<input data-note-interaction="label" value="${e(draft.interaction.label)}"></label><label>Hint<textarea data-note-interaction="hint">${e(draft.interaction.hint)}</textarea></label><label>Next discovery title<input data-note-interaction="nextTitle" value="${e(draft.interaction.nextTitle)}"></label><label>Next discovery information<textarea data-note-interaction="nextContent">${e(draft.interaction.nextContent)}</textarea></label><button type="button" data-note-example>Try the Pigeon Pea discovery example</button>`:''}${draft.type==='dynamic'?`<label>Start with<select data-note-starter><option value="">Choose a starter…</option>${DYNAMIC_NOTE_STARTERS.map(item=>`<option value="${item.id}">${e(item.label)}</option>`).join('')}</select></label><h3>Widgets</h3><p>Main spatial Note + optional widgets. Arrangement is automatic.</p><div class="note-widget-editor-list">${draft.widgets.map((item,index)=>{
            const definition=noteWidgetDefinition(item.type);
            return `<details data-widget-edit="${e(item.id)}"><summary>${e(item.title || definition?.label || item.type)}</summary><label>Widget<select data-widget-field="type">${noteWidgetLibrary().map(type=>`<option value="${type.type}" ${item.type===type.type?'selected':''}>${e(type.label)}</option>`).join('')}</select></label><label>Title<input data-widget-field="title" value="${e(item.title)}"></label>${item.type==='image'?`<label>Image URL<input data-widget-config="url" value="${e(item.configuration?.url)}" placeholder="https://…"></label><label>Caption<input data-widget-config="caption" value="${e(item.configuration?.caption)}"></label>`:item.type==='timer'?`${timerEditorFields(item)}`:`<label>${['checklist','plant-list'].includes(item.type)?'One item per line':'Information'}<textarea data-widget-field="content" rows="3">${e(item.content)}</textarea></label>`}<div class="note-widget-order"><button type="button" data-widget-move="-1" ${index===0?'disabled':''}>Move up</button><button type="button" data-widget-move="1" ${index===draft.widgets.length-1?'disabled':''}>Move down</button><button type="button" data-widget-remove>Remove widget</button></div></details>`;
        }).join('')}</div><button type="button" data-add-widget ${draft.widgets.length>=WIDGET_LIMIT?'disabled':''}>+ ADD WIDGET</button>${draft.widgets.length>=WIDGET_LIMIT?'<small>Five widgets keeps this Note readable in space.</small>':''}${libraryOpen?`<div class="note-widget-library" aria-label="Widget Library">${['Information','Activity','Garden tools'].map(category=>`<section><h4>${category.toUpperCase()}</h4>${noteWidgetLibrary().filter(item=>item.category===category).map(item=>`<button type="button" data-widget-add="${item.type}"><span>${item.icon}</span><strong>${e(item.label)}</strong><small>${e(item.description)}</small></button>`).join('')}</section>`).join('')}</div>`:''}`:''}`;
    };
    const click=event=>{
        const target=event.target.closest('button');if(!target)return;
        if(target.dataset.noteType){draft.type=target.dataset.noteType;render();}
        else if(target.hasAttribute('data-add-widget')){libraryOpen=!libraryOpen;render();}
        else if(target.dataset.widgetAdd && draft.widgets.length<WIDGET_LIMIT){draft.widgets.push(createNoteWidget(target.dataset.widgetAdd));libraryOpen=false;render();}
        else if(target.hasAttribute('data-note-example')){draft.interaction={label:'I found it',hint:'Look for three leaflets near the edge of the garden.',nextTitle:'Find a mulch plant',nextContent:'Look for a plant whose leaves can help cover the soil.'};onStarter({title:'Find a Pigeon Pea',content:'Look around this area for a plant with trifoliate leaves.'});render();}
        else {const id=target.closest('[data-widget-edit]')?.dataset.widgetEdit,index=draft.widgets.findIndex(item=>item.id===id);if(index<0)return;if(target.hasAttribute('data-widget-remove'))draft.widgets.splice(index,1);if(target.dataset.widgetMove){const next=index+Number(target.dataset.widgetMove);if(next>=0 && next<draft.widgets.length)[draft.widgets[index],draft.widgets[next]]=[draft.widgets[next],draft.widgets[index]];}render();}
    };
    const change=event=>{
        const target=event.target;
        if(target.dataset.noteInteraction){draft.interaction[target.dataset.noteInteraction]=target.value;return;}
        if(target.hasAttribute('data-note-starter') && target.value){const starter=noteStarter(target.value);draft=starter.note;onStarter(starter);render();return;}
        const item=draft.widgets.find(item=>item.id===target.closest('[data-widget-edit]')?.dataset.widgetEdit);if(!item)return;
        if(target.dataset.widgetField){if(target.dataset.widgetField==='type'){const fresh=createNoteWidget(target.value);Object.assign(item,fresh,{id:item.id});render();}else item[target.dataset.widgetField]=target.value;}
        if(target.dataset.widgetConfig)item.configuration[target.dataset.widgetConfig]=target.value;
        if(target.hasAttribute('data-widget-minutes'))item.configuration.seconds=Math.max(1,Number(target.value)||1)*60;
        if(target.hasAttribute('data-widget-days'))item.configuration.seconds=Math.max(0,Math.min(3650,Math.round(Number(target.value)||0)))*86400;
    };
    root.addEventListener('click',click);root.addEventListener('input',change);root.addEventListener('change',change);render();
    return {value:()=>validateSpatialNote(draft),destroy(){root.removeEventListener('click',click);root.removeEventListener('input',change);root.removeEventListener('change',change);}};
}
