// Curated trial content for the two plants in the introduction. Keep IDs stable:
// saved cell paths and Control-panel selections depend on them.
const pigeonSource = { id: 'pigeon-pea-agroforestry', title: 'World Agroforestry — Cajanus cajan species profile', url: 'https://apps.worldagroforestry.org/treedb2/speciesprofile.php?Spid=408' };
const moringaSource = { id: 'moringa-agroforestry', title: 'World Agroforestry — Moringa oleifera species profile', url: 'https://apps.worldagroforestry.org/treedb2/speciesprofile.php?Spid=1169' };
const moringaFoodSource = { id: 'moringa-feedi', title: 'Feedipedia — Moringa oleifera', url: 'https://www.feedipedia.org/node/124' };

const extra = (id, parentId, title, preview, body, options = {}) => ({
    id, parentId, title, preview, body, informationType: options.informationType || 'fact',
    evidenceStatus: options.evidenceStatus || 'sourced', status: 'published',
    sourceIds: options.sourceIds || [], safetyNote: options.safetyNote || ''
});

export const PIGEON_PEA_TRIAL = Object.freeze({
    sources: [pigeonSource],
    bodies: {
        'food-forest-layer': 'Pigeon pea usually occupies the productive shrub layer rather than the permanent canopy. Its branching form can shelter young plants, but its shade and root competition change as it grows; watch the neighbours before deciding how long to keep it.',
        uses: 'Follow the plant from tender pod to green seed, mature dry pulse, leafy fodder and woody stem. Each use belongs to a different harvest stage, and food uses require correct identification and appropriate cooking.',
        craft: 'Older stems offer short-lived stakes, light woven material and fuel. Select material by strength and intended lifetime; do not treat the soft new growth like finished timber.',
        seed: 'Seed is the usual way to establish pigeon pea. Preserve the seed line, harvest year and growing conditions alongside the seed, because that context is as valuable as the seed itself.',
        taxonomy: 'The accepted name Cajanus cajan places this plant in Fabaceae. A common name alone is not enough for confident identification or for linking a local record to a scientific reference.',
        morphology: 'Read leaves, pea-shaped flowers, branching habit and pods together. One feature may vary with variety, age or growing conditions, while the combination gives a more dependable identification.',
        'common-names': 'Pigeon pea has many regional names. Attach a language, place and contributor to any added name so a shared word does not silently erase local meaning.',
        'range-and-movement': 'The plant is cultivated across warm regions, but origin, domestication and later movement are different questions. Keep a dated source with each historical claim.',
        'cultural-history': 'Food preparations and growing practices have long histories in different communities. Add specific stories with their knowledge holders and permissions, rather than presenting one practice as universal.',
        climate: 'Pigeon pea is a warm-season plant. Its flowering, survival and length of production depend on local temperatures, day length, rainfall and the variety planted.',
        light: 'Give the plant enough direct light for sturdy growth and pod set. Also measure the light it removes from younger neighbours as its crown expands.',
        soil: 'Drainage and active soil biology matter for establishment and nodulation. The plant may tolerate relatively poor soils, but poor growth should prompt observation, not an assumption that nitrogen fixation will solve everything.',
        water: 'New seedlings need moisture to establish. Older plants can use deeper soil water, yet prolonged drought can still reduce growth and pod yield.',
        maintenance: 'Manage this short-lived shrub for the job it is doing: harvest, living shelter, mulch or seed. Pruning, health checks and eventual replacement all change the surrounding planting.',
        'nitrogen-fixation': 'Pigeon pea can fix atmospheric nitrogen through compatible root bacteria. Much of that nitrogen may leave in harvested seed; neighbours do not receive an instant fertilizer dose. Roots, leaf fall and returned prunings contribute over time as material decomposes.',
        'pollinator-resource': 'Pigeon pea flowers can be visited by bees and other insects. Watch actual visitors at this site, and compare flowering dates with neighbouring plants; a flower is a resource only when a visitor can reach it at the right time.',
        'fresh-peas': 'Shell green, developed seeds before the pod dries and cook them as a fresh legume. Their tender texture suits stews, curries and vegetable dishes; record the cultivar and recipe because cooking time changes with maturity.',
        'young-pods': 'Very young pods may be cooked before the seeds are prominent. Once fibrous, the pod is not the same vegetable: leave it to develop green seeds or a dry pulse instead.',
        'dried-pulse': 'Let pods mature and dry, then shell, sort and store the seeds. Whole dried pigeon pea and split, dehulled dhal are different kitchen forms; both need suitable cooking before serving.',
        'soak-and-cook': 'Inspect and rinse dry seed, soak where the recipe calls for it, discard the soaking water if that is the chosen method, and cook thoroughly until the pulse is tender. Storage age, whole versus split form and altitude change the time required.'
    },
    nodes: [
        extra('nitrogen-transfer', 'nitrogen-fixation', 'Where nitrogen goes', 'Harvest and residues matter', 'Fixation supports the pigeon pea plant first. Nitrogen exported in seed is removed from the site; nitrogen in roots, fallen leaves and returned prunings may become available after decomposition. Compare a harvested-and-cleared plant with one whose residues remain.', { informationType: 'guidance' }),
        extra('nodule-field-check', 'root-nodule-symbiosis', 'Nodule field check', 'Observe, do not assume', 'With permission, inspect a small root sample from a representative plant. Record whether nodules are present and the plant’s condition; nodule presence alone does not measure a nitrogen-fixation rate.', { informationType: 'local_observation', evidenceStatus: 'local_observation' }),
        extra('flower-to-pod', 'pollinator-resource', 'Flower to pod', 'Compare visits with pod set', 'Record flowering dates, insect visits and later pod set on the same branches. This can reveal local patterns without claiming that one visitor caused every pod.', { informationType: 'local_observation', evidenceStatus: 'local_observation' }),
        extra('root-and-soil', 'ecological-functions', 'Roots and soil', 'Deep roots and soil structure', 'The root system can explore deeper soil and help create channels as roots grow and decay. Soil texture, compaction and moisture determine what this means in a particular bed.'),
        extra('companion-light-window', 'nurse-plant', 'Companion light window', 'Shelter now, light later', 'Use the young shrub for temporary shelter, then check whether its canopy is beginning to suppress the intended long-term crop. Prune or replace it according to observed light and growth, not a fixed calendar.', { informationType: 'guidance' }),
        extra('harvest-stages', 'culinary', 'Three harvest stages', 'Pod, green seed, dry pulse', 'The tender pod, shelled green seed and fully dry seed are three distinct ingredients. Label each harvest stage before choosing a recipe so the preparation matches the texture.'),
        extra('green-seed-dishes', 'fresh-peas', 'Green-seed dishes', 'Stews and curries', 'Cook shelled green pigeon peas in a stew, curry or vegetable dish where they retain some shape. Taste for tenderness and record the household or published recipe that guided the preparation.', { informationType: 'practice' }),
        extra('tender-pod-dishes', 'young-pods', 'Tender-pod dishes', 'Cook before fibres toughen', 'Select very young pods with little developed seed, trim and cook according to a trusted local recipe. Test tenderness first; mature pods are better treated as a seed harvest.', { informationType: 'practice' }),
        extra('split-dhal', 'dried-pulse', 'Split dhal', 'Dehulled, split dry seed', 'Dried pigeon pea may be dehulled and split for dhal. The split form cooks differently from the whole seed and is used in soups, dals and other regional dishes; retain the named recipe tradition.', { informationType: 'practice' }),
        extra('dry-seed-storage', 'dried-pulse', 'Food storage', 'Dry, clean and labelled', 'Dry shelled seed thoroughly, remove damaged seed, and store it clean and labelled in a pest-resistant container. Recheck for moisture or insects before cooking.', { informationType: 'guidance' }),
        extra('leafy-fodder', 'animal-fodder', 'Leafy fodder', 'Feed is species-specific', 'Leaves and tender stems may be used as forage in some livestock systems. Their share of a ration should be decided with species-specific feeding guidance, not inferred from human food uses.', { informationType: 'guidance', safetyNote: 'Do not use as a sole feed or assume suitability for every animal.' }),
        extra('seedling-stage', 'direct-sowing', 'Seedling stage', 'Protect a slow start', 'Mark the sowing position and keep competing growth from overwhelming small seedlings. Record emergence, insect damage and moisture so later performance has an understandable starting point.', { informationType: 'guidance' }),
        extra('pod-seed-count', 'pod-identification', 'Pod and seed count', 'Compare several pods', 'Count seeds in several mature pods and photograph their shape and colour. Variation within a plant is normal; use this as a supporting record rather than a single-feature identification test.', { informationType: 'local_observation', evidenceStatus: 'local_observation' }),
        extra('flowering-calendar', 'phenology', 'Flowering calendar', 'Link season to harvest', 'Record the first flowers, peak flowering, first green pods and dry-pod harvest. Comparing years can reveal a variety’s response to day length, rainfall or pruning at this site.', { informationType: 'local_observation', evidenceStatus: 'local_observation' }),
        extra('post-harvest-residues', 'harvest', 'After harvest', 'Keep or remove biomass deliberately', 'After a pulse harvest, decide whether healthy stems and foliage will become mulch, stakes or be removed. This choice changes how much plant material stays in the food-forest system.', { informationType: 'guidance' })
    ]
});

export const MORINGA_TRIAL = Object.freeze({
    sources: [moringaSource, moringaFoodSource],
    bodies: {
        'food-forest': 'Moringa is a fast-growing, prunable tree that can offer edible foliage, light shade, flowers and biomass. Its crown and roots still compete for resources; design around observed light and water rather than promising automatic companion benefits.',
        uses: 'Moringa is used for leaves, tender pods, flowers, mature seeds and oil, as well as mulch and light garden material. Plant parts are not interchangeable. Roots and bark need a separate safety boundary and are not presented here as foods to try.',
        propagation: 'Moringa can start from seed or stem cuttings. Keep the parent source and method with each plant, then compare rooting, survival and later form in the actual planting place.',
        'scientific-information': 'Use the accepted botanical name, Moringaceae family, compound foliage, pale flowers, long three-sided pods and winged seed together when identifying this tree.',
        'historical-data': 'Moringa has a South Asian origin and a much wider cultivated history. A local food tradition or name should be attached to a place and knowledge source rather than treated as a single worldwide practice.',
        cultivation: 'Warmth, light, drainage, early watering and pruning shape a moringa tree. Growth may be fast in favourable conditions, but cool weather, saturated soil and poor establishment can change the result.',
        'moringa-forest-layer': 'Moringa can be managed as a low, open tree or allowed to grow taller. Pruning changes both harvest reach and the light pattern below; look at the space through the year.',
        'moringa-relationships': 'The canopy, flowers and prunings create possible connections with nearby plants and insects. Note who visits the flowers, where shade falls and what happens to mulch before claiming a benefit.',
        'moringa-culinary': 'Read moringa by plant part and harvest stage: tender leaves, flowers, young pods, mature seeds and seed oil each have different food histories and handling. Roots and bark are not recommended here for eating because safety is uncertain.',
        'moringa-leaf-harvest': 'Pick clean leaves from a correctly identified, untreated tree. Remove tougher stems as the dish requires; leaves can be cooked as greens or dried for a leaf powder. Record drying and storage conditions instead of making health claims.',
        'moringa-pod-harvest': 'Young green pods are harvested while the flesh is tender and cooked in curries, soups or stews. Older pods become fibrous and develop mature seed: record the stage and use a preparation suited to that ingredient.',
        'moringa-seed': 'Collect mature seed from dry pods and keep the seed lot labelled. Seed-grown trees may differ from cuttings in early root and stem development; compare survival locally.',
        'moringa-cuttings': 'Healthy mature stem cuttings can establish a new tree where climate and handling allow. Track rooting and stability; a cutting that makes leaves is not necessarily well anchored yet.',
        'moringa-botanical-name': 'Moringa oleifera is the accepted botanical name used for this trial plant. Confirm the identity before applying any food or growing information.',
        'moringa-family': 'Moringa belongs to Moringaceae, not to the legume family. Do not infer nitrogen fixation from its green foliage or its role in a food forest.',
        'moringa-growth-form': 'A fast-growing, soft-wooded small tree with a light, branching crown. Height and shape depend strongly on pruning and growing conditions.',
        'moringa-origin': 'Moringa oleifera is generally described as native to the northwestern Indian subcontinent. Cultivation elsewhere has a long history, so distinguish native range from a local introduction story.',
        'moringa-food-cultures': 'Leaves and pods are used in many regional cuisines, with particular emphasis varying by place. Add a named recipe and contributor for a specific cultural practice rather than assigning one dish to everyone.',
        'moringa-climate': 'Moringa grows best in warm conditions and can lose foliage or suffer damage in cold weather. Compare wet and dry seasons locally; drought tolerance does not guarantee a strong leaf or pod harvest.',
        'moringa-care': 'Give a young tree light, drainage and enough establishment water. Later, prune for reachable harvests and adjust care to its actual regrowth and the needs of neighbours.'
    },
    nodes: [
        extra('food-forest', null, 'Food Forest', 'A prunable food and support tree', 'Moringa is a fast-growing, prunable tree that can offer edible foliage, light shade, flowers and biomass. Its crown and roots still compete for resources; design around observed light and water rather than promising automatic companion benefits.', { informationType: 'category' }),
        extra('uses', null, 'Uses', 'Food, materials and boundaries', 'Moringa is used for leaves, tender pods, flowers, mature seeds and oil, as well as mulch and light garden material. Plant parts are not interchangeable. Roots and bark need a separate safety boundary and are not presented here as foods to try.', { informationType: 'category' }),
        extra('propagation', null, 'Propagation', 'Seed and stem cuttings', 'Moringa can start from seed or stem cuttings. Keep the parent source and method with each plant, then compare rooting, survival and later form in the actual planting place.', { informationType: 'category' }),
        extra('scientific-information', null, 'Scientific Information', 'Identity and plant form', 'Use the accepted botanical name, Moringaceae family, compound foliage, pale flowers, long three-sided pods and winged seed together when identifying this tree.', { informationType: 'category' }),
        extra('historical-data', null, 'Historical Data', 'Origin and living traditions', 'Moringa has a South Asian origin and a much wider cultivated history. A local food tradition or name should be attached to a place and knowledge source rather than treated as a single worldwide practice.', { informationType: 'category' }),
        extra('cultivation', null, 'Cultivation', 'Care through the seasons', 'Warmth, light, drainage, early watering and pruning shape a moringa tree. Growth may be fast in favourable conditions, but cool weather, saturated soil and poor establishment can change the result.', { informationType: 'category' }),
        extra('moringa-flower-resource', 'moringa-relationships', 'Flower resource', 'Nectar and insect visits', 'Flowers can attract bees and other visitors. Observe which insects actually visit, when flowers open and whether nearby plants offer overlapping bloom; do not infer a pollination benefit from flowers alone.'),
        extra('moringa-not-nitrogen-fixer', 'moringa-relationships', 'Nitrogen distinction', 'Biomass is not fixation', 'Moringa is not a legume or a recognised root-nodule nitrogen fixer. Returned leaves may recycle nutrients already taken up by the tree, but they do not create a new nitrogen-fixing relationship like pigeon pea.'),
        extra('moringa-root-role', 'moringa-relationships', 'Root role', 'Anchorage and water access', 'Roots anchor the tree and draw water and nutrients from surrounding soil. Give young trees room to establish and watch competition near small neighbours; root form varies with propagation method and soil.'),
        extra('moringa-shade-map', 'moringa-canopy-management', 'Shade map', 'Notice moving light', 'Mark the morning and afternoon shade edge before and after pruning. Use the comparison to decide where a sun-loving understory plant can actually thrive.', { informationType: 'local_observation', evidenceStatus: 'local_observation' }),
        extra('moringa-leaves-kitchen', 'moringa-culinary', 'Leaves in the kitchen', 'Cooked greens or dried leaf', 'Strip leaflets from coarse stalks as needed and cook them as greens in soups, stews or sauces. Dried leaf powder is a different form: keep it clean, dry and labelled, and use a trusted preparation rather than treating it as a medicine.', { informationType: 'practice' }),
        extra('moringa-flowers-kitchen', 'moringa-culinary', 'Flowers in the kitchen', 'An occasional cooked ingredient', 'Flowers are used as a cooked vegetable in some food traditions. Harvest from a correctly identified, unsprayed tree and keep the recipe source; taking flowers also reduces the number available to develop into pods.', { informationType: 'practice', safetyNote: 'Use only correctly identified, clean flowers and a reliable food preparation.' }),
        extra('moringa-tender-pods', 'moringa-culinary', 'Tender pods', 'Harvest before fibres harden', 'Young pods, often called drumsticks, are cut while tender and cooked in curries, soups or stews. The outer pod can become fibrous with age; the edible portion and method depend on the recipe.', { informationType: 'practice' }),
        extra('moringa-mature-seeds', 'moringa-culinary', 'Mature seeds and oil', 'A separate harvest', 'When pods dry, collect the mature winged seeds. The seeds are a source of edible oil after proper processing, but they are not the same ingredient as a tender pod; use a verified food-grade product or recipe.', { informationType: 'guidance', safetyNote: 'Do not treat seed intended for water treatment or planting as prepared food.' }),
        extra('moringa-roots-boundary', 'moringa-culinary', 'Roots and bark boundary', 'Historical use is not a recipe', 'Some references record root use as a pungent condiment, but also warn of possible toxicity. This demo does not recommend eating roots or bark; record a historical claim with its source without turning it into preparation instructions.', { informationType: 'guidance', sourceIds: ['moringa-feedi'], safetyNote: 'Do not eat moringa roots or bark based on this template.' }),
        extra('moringa-culinary-stage-map', 'moringa-culinary', 'Plant-part map', 'Leaves to mature pods', 'Leaves, flowers, tender pods and mature seeds are separate harvests. Write down the plant part, stage, cleaning, cooking or processing and named recipe source before comparing their uses.'),
        extra('moringa-seed-storage', 'moringa-seed', 'Seed storage', 'Dry and label the lot', 'Let mature pods dry, remove seed and store it clean, dry and labelled with harvest date and parent tree. Trial a small portion before relying on older seed.', { informationType: 'guidance' }),
        extra('moringa-cutting-source', 'moringa-cuttings', 'Cutting source', 'Track parent and stem age', 'Record which tree supplied a cutting, the stem maturity, planting date and rooting result. This makes a later comparison with seed-grown trees meaningful.', { informationType: 'practice' }),
        extra('moringa-flower-form', 'moringa-growth-form', 'Flowers', 'Pale clustered flowers', 'Moringa bears pale cream to white flowers in clusters. Record the flowering season and compare flowers with leaf and pod characters for identification.'),
        extra('moringa-pod-form', 'moringa-growth-form', 'Pods and seed', 'Long three-sided pod', 'The long capsule develops three pronounced angles and contains winged seeds when mature. A tender food pod and a dry seed pod look and handle differently.'),
        extra('moringa-root-form', 'moringa-growth-form', 'Roots', 'Structure, not a food cue', 'Root development supports anchorage and access to soil water. Its shape depends on whether the plant began from seed or a cutting; root appearance should not be used as a reason to consume it.'),
        extra('moringa-origin-record', 'moringa-origin', 'Local introduction', 'Who brought this tree here?', 'For this project, record the seed or cutting source, date of planting and contributor. A local introduction record is distinct from the species’ native range.', { informationType: 'local_observation', evidenceStatus: 'local_observation' }),
        extra('moringa-cool-weather', 'moringa-climate', 'Cool-weather response', 'Check cold exposure', 'Record leaf drop, tip damage and regrowth after cool periods. Protecting an establishing tree or choosing a warmer position should be based on local conditions.', { informationType: 'guidance' }),
        extra('moringa-harvest-regrowth', 'moringa-pruning-cycle', 'Leaf harvest and regrowth', 'Leave a working canopy', 'Frequent leaf picking and hard pruning both remove photosynthetic tissue. Compare the amount taken with the speed of regrowth and reduce harvest pressure if the tree weakens.', { informationType: 'guidance' }),
        extra('moringa-water-after-pruning', 'moringa-care', 'Water after pruning', 'Observe demand, avoid saturation', 'A pruned tree has less leaf area and may use water differently. Check soil moisture before watering heavily, especially where drainage is slow.', { informationType: 'guidance' })
    ]
});

export function enrichTrialNodes(nodes, trial, defaultSourceId) {
    return [...nodes.map(node => ({
        ...node,
        body: trial.bodies[node.id] ?? node.body,
        sourceIds: node.sourceIds?.length ? node.sourceIds :
            ['local_observation', 'community_contributed'].includes(node.evidenceStatus) ? [] : [defaultSourceId]
    })), ...trial.nodes.map(node => ({ ...node,
        sourceIds: node.sourceIds.length || ['local_observation', 'community_contributed'].includes(node.evidenceStatus)
            ? node.sourceIds : [defaultSourceId]
    }))];
}
