import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { renderLaunchScreen } from '../app/screens/launch.js';

const root = path.resolve(import.meta.dirname, '..');

test('welcome keeps primary roles separate and pairs About with the existing AR demo', () => {
    const app = { innerHTML: '' };
    renderLaunchScreen(app);
    assert.match(app.innerHTML, /Create &amp; Manage/);
    assert.match(app.innerHTML, /Build and manage locations, content and visitor experiences/);
    assert.match(app.innerHTML, /Explore a Place/);
    assert.match(app.innerHTML, /welcome-complementary-grid/);
    assert.match(app.innerHTML, /About This Tool/);
    assert.match(app.innerHTML, /Understand what NourishlandXR is and what it can help you build/);
    assert.match(app.innerHTML, /TRY IT NOW/);
    const header = app.innerHTML.slice(app.innerHTML.indexOf('intro-heading'), app.innerHTML.indexOf('</div>', app.innerHTML.indexOf('intro-heading')) + 6);
    assert.match(header, /Plant literacy/);
    assert.match(header, /welcome-version-badge/);
    assert.match(header, /· DEMO/);
    assert.doesNotMatch(app.innerHTML, /welcome-label">DEMO/);
    assert.match(app.innerHTML, /Place a living story in your space/);
    assert.match(app.innerHTML, /openTemporaryArDemoWindow/);
    assert.ok(app.innerHTML.indexOf('welcome-complementary-grid') > app.innerHTML.indexOf('role-grid'));
    assert.doesNotMatch(app.innerHTML, /assets\/herov2\.png/);
});

test('About This Tool explains the concept without tutorial instructions', () => {
    const source = fs.readFileSync(path.join(root, 'app/screens/projectDashboard.js'), 'utf8');
    const aboutStart = source.indexOf("if (feature === 'About This Tool')");
    const aboutEnd = source.indexOf("app.innerHTML = `<div class=\"screen\">", aboutStart);
    const aboutSource = source.slice(aboutStart, aboutEnd);
    assert.match(aboutSource, /What is NourishlandXR\?/);
    assert.match(aboutSource, /place-based tool that connects information directly to real environments/);
    assert.match(aboutSource, /How it works/);
    assert.match(aboutSource, /Built for food literacy/);
    assert.match(aboutSource, /turns knowledge about a place into something you can see, edit and share/);
    assert.doesNotMatch(aboutSource, /Choose your path|Select a location|Explore with AR|Demo note/);
    assert.doesNotMatch(aboutSource, /<ol>|<li>/);
});

test('visitor project selection opens the welcome page without a repeated card action', () => {
    const source = fs.readFileSync(path.join(root, 'app/screens/explorer.js'), 'utf8');
    assert.doesNotMatch(source, /<span>Explore this location<\/span>/i);
    assert.match(source, /renderVisitorLocationIntro/);
    assert.match(source, /Explore in AR/);
    assert.match(source, /Browse Content/);
    assert.match(source, /const projects = \(await loadProjects\(\)\)/);
    assert.match(source, /V2 preview · project view under development/);
    assert.match(source, /privatePreview = creatorPreview \|\| explorePreview/);
    assert.match(source, /Draft content is not published to visitors/);
});

test('AR entry is gated by preparation and only Start AR Mode launches AR', () => {
    const source = fs.readFileSync(path.join(root, 'app/screens/explorer.js'), 'utf8');
    assert.match(source, /NourishlandXR uses your phone’s camera/);
    assert.match(source, /When prompted, please allow access to your camera and location/);
    assert.match(source, />Start AR Mode</);
    assert.match(source, />Go Back</);
});

test('creator dashboard prioritizes Open AR while retaining quiet management and project settings', () => {
    const source = fs.readFileSync(path.join(root, 'app/screens/projectDashboard.js'), 'utf8');
    const entrySource = fs.readFileSync(path.join(root, 'app/components/projectEntry.js'), 'utf8');
    assert.match(entrySource, />OPEN AR</);
    assert.match(entrySource, /Unplaced Bag/);
    assert.doesNotMatch(entrySource, />Work Mode</);
    assert.doesNotMatch(entrySource, />Quick Access</);
    assert.match(source, /openArAction/);
    assert.match(source, /addUnplacedAction/);
    assert.match(source, /renderContentMode/);
    assert.match(source, /Field Guide/);
    assert.match(source, /Stories &amp; Checkpoints/);
    assert.match(source, /Unplaced Bag/);
    assert.match(source, /Add without AR/);
    assert.match(source, /Stories and Focus Elements/);
    assert.match(source, /Project Settings/);
    assert.match(source, /Manage entrances and experience starting points/);
    assert.match(source, /Change Theme/);
    assert.match(source, /LIGHT \(White\)/);
    assert.match(source, /DARK \(Black\)/);
    assert.match(source, /FOREST DARK \(Green\)/);
    assert.match(source, /FOREST LIGHT/);
    assert.match(source, /CYBER \(Gray \/ Purple\)/);
    assert.match(source, /projectThemeSaveQueues/);
    assert.match(source, /requestedProjectThemes/);
    assert.match(source, /Applying \$\{theme\.replace/);
    assert.match(source, /style\.colorScheme/);
    assert.match(source, /Backup Project to File/);
    assert.match(source, /Exports a configuration file containing all project data/);
    assert.match(source, /Coming Soon/);
    assert.match(source, /deleteProjectFromSettings/);
    assert.match(source, /window\.confirm/);
    assert.match(source, /deleteProjectFromSettings\('\$\{encoded\(project\.id\)\}', '\$\{encoded\(project\.name\)\}'\)/);
    const deleteSource = source.slice(source.indexOf('export async function deleteProjectFromSettings'), source.indexOf('export async function renderBrowseContent'));
    assert.match(deleteSource, /pendingThemeSave/);
    assert.match(deleteSource, /deleteProjectOnDisk\(projectId\)/);
    assert.doesNotMatch(deleteSource, /projectById/);
    assert.match(source, /Restart Tutorial for This Project/);
    assert.match(source, /Reset Learning Tips/);
    assert.match(source, /Tutorial Mode/);
    assert.match(source, /recordTutorialEvent/);
    assert.match(entrySource, /dashboard-open-ar/);
    assert.match(entrySource, />OPEN AR</);
    assert.match(entrySource, /Unplaced Bag/);
    assert.doesNotMatch(entrySource, />Quick Access</);
    assert.doesNotMatch(entrySource, /Add content to this location/);
    assert.doesNotMatch(entrySource, /<strong>Add \$\{item\.label\}<\/strong>/);
    assert.match(entrySource, /project-areas-section/);
    assert.match(entrySource, /project-area-link/);
    assert.match(source, /areas: areaLinks/);
    assert.match(source, /renderProjectAreaDashboard/);
    assert.match(entrySource, />Search</);
    assert.match(entrySource, /Search this project/);
    assert.match(entrySource, /data-project-search-item/);
    assert.match(source, /buildProjectSearchItems/);
    assert.match(source, /loadPlantLibrary/);
    assert.match(source, /loadPlantProfile/);
    assert.match(source, /filterProjectSearch/);
    assert.match(entrySource, /Unplaced/);
    assert.match(entrySource, /Project Status/);
    assert.match(entrySource, /dashboard-identity/);
    assert.doesNotMatch(entrySource, /dashboard-introduction/);
    assert.match(entrySource, /tutorial-spotlight-callout/);
    assert.match(entrySource, /tutorial-spotlight-shield/);
    assert.match(entrySource, /contextual-guidance/);
    assert.match(entrySource, /First-use guidance/);
    assert.match(entrySource, /Skip Tutorial/);
    assert.match(entrySource, />See all</);
    assert.match(entrySource, /No entries have been added yet/);
    assert.match(entrySource, />Date</);
    assert.match(entrySource, />Added by</);
    assert.match(source, /renderAllProjectEntries/);
    assert.match(source, /filterAllProjectEntries/);
    assert.match(source, /Search entries/);
    assert.match(source, /entryCreatorLabel/);
    const changesRowSource = entrySource.slice(entrySource.indexOf('function latestEntryRow'), entrySource.indexOf('export function renderProjectEntry'));
    assert.doesNotMatch(changesRowSource, /\$\{item\.area\}|entry-status-/);
});

test('fresh projects can start freely and place Starting Point or Area markers in AR', () => {
    const dashboardSource = fs.readFileSync(path.join(root, 'app/screens/projectDashboard.js'), 'utf8');
    const mainSource = fs.readFileSync(path.join(root, 'app/main.js'), 'utf8');
    assert.match(mainSource, /window\.renderProjectDashboard\(encodeURIComponent\(created\.id\)\)/);
    assert.match(dashboardSource, /Place Starting Point in AR/);
    assert.doesNotMatch(dashboardSource.slice(dashboardSource.indexOf('export async function renderNewLocationSetup'), dashboardSource.indexOf('export async function renderAddToLocation')), /Place Area Marker in AR/);
    assert.match(dashboardSource, /1\. Open AR/);
    assert.match(dashboardSource, /2\. Aim at an object/);
    assert.match(dashboardSource, /3\. Tap to place/);
    assert.match(dashboardSource, /No code is required/);
    assert.match(dashboardSource, /Outdoor Area — garden, park, nursery, farm section/);
    assert.match(dashboardSource, /Indoor Area — greenhouse, building, covered growing area/);
    assert.match(dashboardSource, /Bed or Plot — garden bed, terrace, production row/);
    assert.match(dashboardSource, /Room — classroom, propagation room, restaurant/);
    assert.match(dashboardSource, /Enclosure — pen, protected garden, fenced compartment/);
    assert.match(dashboardSource, /Path or Route — trail, tour route, nursery lane/);
    assert.match(dashboardSource, /Other — anything that doesn’t fit/);
    assert.match(dashboardSource, /renderAreaRequired/);
    assert.match(dashboardSource, /ensureProjectLocation/);
    assert.match(dashboardSource, /Main Location/);
    assert.match(dashboardSource, />Create Area</);
    assert.match(dashboardSource, /Is this where your Starting Point will be/);
    assert.match(dashboardSource, /area_explained/);
    assert.match(dashboardSource, /first_area_created_or_selected/);
    assert.match(dashboardSource, /meaningful section inside a Location/);
});

test('quick access creation is minimal and separates Area assignment from placement', () => {
    const source = fs.readFileSync(path.join(root, 'app/screens/fieldMarker.js'), 'utf8');
    assert.match(source, /<label for="fieldArea">Area<\/label>/);
    assert.match(source, /Reuse Plant Profile/);
    assert.match(source, /Unassigned — decide later/);
    assert.match(source, /Create a new Area/);
    assert.match(source, /Placement status:<\/strong> Not yet placed/);
    assert.doesNotMatch(source, /<label>Project<\/label>/);
    assert.doesNotMatch(source, /<label>Location<\/label>/);
    assert.doesNotMatch(source, /<label>Site<\/label>/);
    assert.doesNotMatch(source, /<label>Marker Type<\/label>/);
});

test('temporary AR demo places a story board and three guided spatial elements without saving', () => {
    const source = fs.readFileSync(path.join(root, 'app/screens/temporaryArDemo.js'), 'utf8');
    const styles = fs.readFileSync(path.join(root, 'app/style.css'), 'utf8');
    assert.match(source, /Tap to place the story/);
    assert.match(source, /const DEMO_SEQUENCE = \['plant', 'note', 'zone'\]/);
    assert.match(source, /Every place holds more than we first see/);
    assert.match(source, /Area · Citrus Guild/);
    assert.match(source, /function createSpatialKnowledgeTexture/);
    assert.match(source, /record\.demoExpanded/);
    assert.match(source, /Begin building/);
    assert.match(source, /See how Areas work/);
    assert.match(source, /markers\.length >= 4/);
    assert.match(source, /createMinimalMarkerDraft/);
    assert.match(source, /relateMinimalMarkers/);
    assert.match(source, /Use Lemon Myrtle preset/);
    assert.match(source, /scheduleRecordUpdate/);
    assert.match(source, /createBoundaryTexture/);
    assert.match(styles, /tryit-sim-marker-zone\.is-expanded::before/);
    assert.match(source, /Search plant presets<input value="Lemon Myrtle" readonly>/);
    assert.doesNotMatch(source, /tryit-panel/);
    assert.match(styles, /\.tryit-demo\.is-immersive \.tryit-sim-marker \{ display: none !important;/);
    assert.match(source, /function placeMarker/);
    assert.match(source, /function createMarkerTexture/);
    assert.doesNotMatch(source, /Loading Dashboard|Place Your Dashboard|draggable-window/);
    assert.match(source, /isSessionSupported\('immersive-ar'\)/);
    assert.match(source, /makeXRCompatible/);
    assert.match(source, /new XRWebGLLayer/);
    assert.match(source, /requestAnimationFrame\(draw\)/);
    assert.match(source, /requiredFeatures: \['dom-overlay', 'hit-test'\]/);
    assert.match(source, /requestHitTestSource/);
    assert.match(source, /TEXTURE_WRAP_S, gl\.CLAMP_TO_EDGE/);
    assert.match(source, /TEXTURE_WRAP_T, gl\.CLAMP_TO_EDGE/);
    assert.match(source, /Finish demo/);
    assert.match(source, /spatialPosition\(hitMatrix, viewerMatrix/);
    assert.doesNotMatch(source, /persistence|apiFetch|fetch\(/);
});

test('new location asks only for core details and supported templates', () => {
    const form = fs.readFileSync(path.join(root, 'app/components/siteForm.js'), 'utf8');
    const templates = fs.readFileSync(path.join(root, 'app/templates/projectTemplates.js'), 'utf8');
    const dashboard = fs.readFileSync(path.join(root, 'app/screens/projectDashboard.js'), 'utf8');
    assert.match(form, /Location name/);
    assert.match(form, /Description \(optional\)/);
    assert.match(form, /projectTemplate/);
    assert.doesNotMatch(form, /projectCoverImage|Suggested Locations/);
    for (const label of ['Food Forest', 'Native Forest', 'Orchard', 'Home Garden', 'Kitchen Garden', 'Plant Nursery', 'Stock Inventory']) {
        assert.match(templates, new RegExp(label));
    }
    assert.match(dashboard, /projectSettingsCoverImage/);
    assert.match(dashboard, /Cover image \(optional\)/);
});
