import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { renderLaunchScreen } from '../app/screens/launch.js';

const root = path.resolve(import.meta.dirname, '..');

test('welcome keeps primary roles separate and pairs About with the existing AR demo', () => {
    const app = { innerHTML: '' };
    renderLaunchScreen(app);
    assert.match(app.innerHTML, /Create &amp; Manage/);
    assert.match(app.innerHTML, /Build and manage locations, content and visitor experiences/);
    assert.match(app.innerHTML, /Explore a Place/);
    assert.match(app.innerHTML, /welcome-complementary-grid/);
    assert.match(app.innerHTML, /About This Experience/);
    assert.match(app.innerHTML, /Understand what NourishlandXR is and what it can help you build/);
    assert.match(app.innerHTML, /Try It Now/);
    assert.match(app.innerHTML, /Experience a quick demonstration of information appearing within a real place/);
    assert.match(app.innerHTML, /openTemporaryArDemoWindow/);
    assert.ok(app.innerHTML.indexOf('welcome-complementary-grid') > app.innerHTML.indexOf('role-grid'));
    assert.doesNotMatch(app.innerHTML, /assets\/herov2\.png/);
});

test('About This Experience explains the concept without tutorial instructions', () => {
    const source = fs.readFileSync(path.join(root, 'app/screens/projectDashboard.js'), 'utf8');
    const aboutStart = source.indexOf("if (feature === 'About This Experience')");
    const aboutEnd = source.indexOf("app.innerHTML = `<div class=\"screen\">", aboutStart);
    const aboutSource = source.slice(aboutStart, aboutEnd);
    assert.match(aboutSource, /What is NourishlandXR\?/);
    assert.match(aboutSource, /dynamic, place-based database that connects information to real environments/);
    assert.match(aboutSource, /More than a map/);
    assert.match(aboutSource, /Build from anywhere/);
    assert.match(aboutSource, /A living record/);
    assert.match(aboutSource, /helps turn knowledge about a place into something organized, visible and connected to the landscape itself/);
    assert.doesNotMatch(aboutSource, /How it works|Choose your path|Select a location|Explore with AR|Demo note/);
    assert.doesNotMatch(aboutSource, /<ol>|<li>/);
});

test('visitor project selection opens the welcome page without a repeated card action', () => {
    const source = fs.readFileSync(path.join(root, 'app/screens/explorer.js'), 'utf8');
    assert.doesNotMatch(source, /<span>Explore this location<\/span>/i);
    assert.match(source, /renderVisitorLocationIntro/);
    assert.match(source, /Explore in AR/);
    assert.match(source, /Browse Content/);
});

test('AR entry is gated by preparation and only Start AR Mode launches AR', () => {
    const source = fs.readFileSync(path.join(root, 'app/screens/explorer.js'), 'utf8');
    assert.match(source, /NourishlandXR uses your phone’s camera/);
    assert.match(source, /When prompted, please allow access to your camera and location/);
    assert.match(source, />Start AR Mode</);
    assert.match(source, />Go Back</);
});

test('creator dashboard exposes equal AR and Content work modes, quick add, search and project settings', () => {
    const source = fs.readFileSync(path.join(root, 'app/screens/projectDashboard.js'), 'utf8');
    const entrySource = fs.readFileSync(path.join(root, 'app/components/projectEntry.js'), 'utf8');
    assert.match(entrySource, />Work Mode</);
    assert.match(source, /label: 'AR Mode'/);
    assert.match(source, /Position and work with content in the landscape/);
    assert.match(source, /label: 'Content Mode'/);
    assert.match(source, /Add and organize content without the camera/);
    assert.doesNotMatch(source, /label: 'Dive straight into AR'/);
    assert.match(source, /renderContentMode/);
    assert.match(source, /Field Guide/);
    assert.match(source, /Stories &amp; Checkpoints/);
    assert.match(source, /Unplaced Content/);
    assert.match(source, /Add without AR/);
    assert.match(source, /Stories and Focus Elements/);
    assert.match(source, /Project Settings/);
    assert.match(source, /Manage entrances and experience starting points/);
    assert.match(source, /Change Theme/);
    assert.match(source, /LIGHT \(White\)/);
    assert.match(source, /DARK \(Black\)/);
    assert.match(source, /FOREST DARK \(Green\)/);
    assert.match(source, /FOREST LIGHT/);
    assert.match(source, /CYBER \(Gray \/ Purple\)/);
    assert.match(source, /projectThemeSaveQueues/);
    assert.match(source, /requestedProjectThemes/);
    assert.match(source, /Applying \$\{theme\.replace/);
    assert.match(source, /style\.colorScheme/);
    assert.match(source, /Backup Project to File/);
    assert.match(source, /Exports a configuration file containing all project data/);
    assert.match(source, /Coming Soon/);
    assert.match(source, /deleteProjectFromSettings/);
    assert.match(source, /window\.confirm/);
    assert.match(source, /deleteProjectFromSettings\('\$\{encoded\(project\.id\)\}', '\$\{encoded\(project\.name\)\}'\)/);
    const deleteSource = source.slice(source.indexOf('export async function deleteProjectFromSettings'), source.indexOf('export async function renderBrowseContent'));
    assert.match(deleteSource, /pendingThemeSave/);
    assert.match(deleteSource, /deleteProjectOnDisk\(projectId\)/);
    assert.doesNotMatch(deleteSource, /projectById/);
    assert.match(source, /Restart Tutorial for This Project/);
    assert.match(source, /Reset Learning Tips/);
    assert.match(source, /Tutorial Mode/);
    assert.match(source, /recordTutorialEvent/);
    assert.match(entrySource, /Quick Access/);
    assert.match(entrySource, /quick-access-icon/);
    assert.match(entrySource, /<strong>\$\{item\.label\}<\/strong>/);
    assert.doesNotMatch(entrySource, /Add content to this location/);
    assert.doesNotMatch(entrySource, /<strong>Add \$\{item\.label\}<\/strong>/);
    assert.match(entrySource, /project-areas-section/);
    assert.match(entrySource, /project-area-link/);
    assert.match(source, /areas: areaLinks/);
    assert.match(source, /renderProjectAreaDashboard/);
    assert.match(entrySource, />Search</);
    assert.match(entrySource, /Search this project/);
    assert.match(entrySource, /data-project-search-item/);
    assert.match(source, /buildProjectSearchItems/);
    assert.match(source, /loadPlantLibrary/);
    assert.match(source, /loadPlantProfile/);
    assert.match(source, /filterProjectSearch/);
    assert.match(entrySource, /Unplaced/);
    assert.match(entrySource, /Project Status/);
    assert.match(entrySource, /dashboard-identity/);
    assert.doesNotMatch(entrySource, /dashboard-introduction/);
    assert.match(entrySource, /tutorial-spotlight-callout/);
    assert.match(entrySource, /tutorial-spotlight-shield/);
    assert.match(entrySource, /contextual-guidance/);
    assert.match(entrySource, /First-use guidance/);
    assert.match(entrySource, /Skip Tutorial/);
    assert.match(entrySource, />See all</);
    assert.match(entrySource, /No entries have been added yet/);
    assert.match(entrySource, />Date</);
    assert.match(entrySource, />Added by</);
    assert.match(source, /renderAllProjectEntries/);
    assert.match(source, /filterAllProjectEntries/);
    assert.match(source, /Search entries/);
    assert.match(source, /entryCreatorLabel/);
    const changesRowSource = entrySource.slice(entrySource.indexOf('function latestEntryRow'), entrySource.indexOf('export function renderProjectEntry'));
    assert.doesNotMatch(changesRowSource, /\$\{item\.area\}|entry-status-/);
});

test('fresh projects receive high guidance and Area-required states are actionable', () => {
    const dashboardSource = fs.readFileSync(path.join(root, 'app/screens/projectDashboard.js'), 'utf8');
    const entrySource = fs.readFileSync(path.join(root, 'app/components/projectEntry.js'), 'utf8');
    assert.match(dashboardSource, /area:\s*\{/);
    assert.match(dashboardSource, /Create your first Area/);
    assert.match(dashboardSource, /Outdoor Area — garden, park, nursery, farm section/);
    assert.match(dashboardSource, /Indoor Area — greenhouse, building, covered growing area/);
    assert.match(dashboardSource, /Bed or Plot — garden bed, terrace, production row/);
    assert.match(dashboardSource, /Room — classroom, propagation room, restaurant/);
    assert.match(dashboardSource, /Enclosure — pen, protected garden, fenced compartment/);
    assert.match(dashboardSource, /Path or Route — trail, tour route, nursery lane/);
    assert.match(dashboardSource, /Other — anything that doesn’t fit/);
    assert.match(dashboardSource, /renderAreaRequired/);
    assert.match(dashboardSource, /ensureProjectLocation/);
    assert.match(dashboardSource, /Main Location/);
    assert.match(dashboardSource, />Create Area</);
    assert.match(dashboardSource, /Is this where your Starting Point will be/);
    assert.match(dashboardSource, /Project → Location → Area → Plant or Note/);
    assert.match(dashboardSource, /area_explained/);
    assert.match(dashboardSource, /first_area_created_or_selected/);
    assert.match(dashboardSource, /meaningful section inside a Location/);
});

test('quick access creation is minimal and separates Area assignment from placement', () => {
    const source = fs.readFileSync(path.join(root, 'app/screens/fieldMarker.js'), 'utf8');
    assert.match(source, /<label for="fieldArea">Area<\/label>/);
    assert.match(source, /Reuse Plant Profile/);
    assert.match(source, /Unassigned — decide later/);
    assert.match(source, /Create a new Area/);
    assert.match(source, /Placement status:<\/strong> Not yet placed/);
    assert.doesNotMatch(source, /<label>Project<\/label>/);
    assert.doesNotMatch(source, /<label>Location<\/label>/);
    assert.doesNotMatch(source, /<label>Site<\/label>/);
    assert.doesNotMatch(source, /<label>Marker Type<\/label>/);
});

test('temporary AR demo is in-memory and supports placement, profile and exit', () => {
    const source = fs.readFileSync(path.join(root, 'app/screens/temporaryArDemo.js'), 'utf8');
    assert.match(source, /Open My Location Dashboard/);
    assert.match(source, /My Location/);
    assert.match(source, /Tag a Nearby Plant/);
    assert.match(source, /Plant List/);
    assert.match(source, /Banana Cavendish/);
    assert.match(source, /Lemon Drop Garcinia/);
    assert.match(source, /Myoga Ginger/);
    assert.match(source, /Jackfruit/);
    assert.match(source, /This is the end of the demo/);
    assert.match(source, /Finish Demo/);
    assert.match(source, /AUGMENTED REALITY/);
    assert.match(source, /temporary-demo-launcher/);
    assert.match(source, /isSessionSupported\('immersive-ar'\)/);
    assert.match(source, /makeXRCompatible/);
    assert.match(source, /new XRWebGLLayer/);
    assert.match(source, /requestAnimationFrame\(draw\)/);
    assert.match(source, /requiredFeatures: \['dom-overlay', 'hit-test'\]/);
    assert.match(source, /requestHitTestSource/);
    assert.match(source, /placedMarker = \{ x: latestHitMatrix/);
    assert.doesNotMatch(source, /persistence|apiFetch|fetch\(/);
});
