import { startArNote } from '../services/arNote.js';
let app, projectUrl, project, hostedMarkers=[];
const get=async url=>{const r=await fetch(url);if(!r.ok)throw new Error(`Missing file: ${url}`);try{return await r.json();}catch{throw new Error(`Invalid JSON: ${url}`);}};
const resolve=(base,relative)=>new URL(relative,base).href;
const fail=e=>app.innerHTML=`<div class="screen"><div class="page-header"><button class="ghost" onclick="window.renderExplorerProjects()">Back</button><h1>Hosted Project unavailable</h1></div><div class="panel"><p>${e.message}</p><p class="meta">Check the URL, hosted files, and CORS policy.</p></div></div>`;
export async function openHostedProject(target,url){app=target;try{projectUrl=new URL(url).href;project=await get(projectUrl);if(!Array.isArray(project.sites))throw new Error('Hosted project has no sites index');hostedMarkers=[];sites();}catch(e){fail(e);}}
function sites(){app.innerHTML=`<div class="screen"><div class="page-header"><button class="ghost" onclick="window.renderExplorerProjects()">Back</button><h1>${project.name}</h1><p class="subtitle">Hosted read-only project</p></div><div class="panel"><button onclick="window.hostedGps()">GPS Mode</button></div>${project.sites.map(s=>`<div class="panel"><div class="list-item"><strong>${s.name}</strong><button onclick="window.openHostedSite('${resolve(projectUrl,s.path)}')">Open</button></div></div>`).join('')}</div>`;}
export async function openHostedSite(url){try{const site=await get(url);if(!Array.isArray(site.places))throw new Error('Hosted site has no places index');app.innerHTML=`<div class="screen"><div class="page-header"><button class="ghost" onclick="window.openHostedProject('${projectUrl}')">Back</button><h1>${site.name}</h1></div>${site.places.map(p=>`<div class="panel"><div class="list-item"><strong>${p.name}</strong><button onclick="window.openHostedPlace('${resolve(url,p.path)}')">Open</button></div></div>`).join('')}</div>`;}catch(e){fail(e);}}
export async function openHostedPlace(url){try{const place=await get(url);if(!Array.isArray(place.markers))throw new Error('Hosted place has no markers index');app.innerHTML=`<div class="screen"><div class="page-header"><button class="ghost" onclick="window.openHostedProject('${projectUrl}')">Back</button><h1>${place.name}</h1></div>${place.markers.map(m=>`<div class="panel"><div class="list-item"><strong>${m.name}</strong><button onclick="window.openHostedMarker('${resolve(url,m.path)}')">Open</button></div></div>`).join('')}</div>`;}catch(e){fail(e);}}
export async function openHostedMarker(url){try{const marker=await get(url);const profile=marker.plant_profile_path?await get(resolve(url,marker.plant_profile_path)):null;let anchor=null,anchorError='';if(marker.anchor_path){try{anchor=await get(resolve(url,marker.anchor_path));}catch(e){anchorError=e.message;}}const ar=anchor?.type==='gps'?`<button onclick="window.startHostedAr('${url}')">Open in AR</button>`:'';app.innerHTML=`<div class="screen"><div class="page-header"><button class="ghost" onclick="window.openHostedProject('${projectUrl}')">Back</button><h1>${profile?.common_name||marker.name}</h1><p class="subtitle">${profile?.scientific_name||marker.type}</p></div><div class="panel"><p>${marker.description||'No description yet.'}</p>${ar}<p id="arStatus" class="meta">${anchorError?`Anchor unavailable: ${anchorError}`:''}</p></div>${profile?`<div class="panel"><h2>Overview</h2><p>${profile.overview||'Not available.'}</p></div>`:''}</div>`;hostedMarkers.push({url,marker,profile,anchor});}catch(e){fail(e);}}

async function collectMarkers(){const found=[];for(const s of project.sites){const su=resolve(projectUrl,s.path),site=await get(su);for(const p of site.places||[]){const pu=resolve(su,p.path),place=await get(pu);for(const m of place.markers||[]){const mu=resolve(pu,m.path),marker=await get(mu);let anchor=null,error='';if(marker.anchor_path)try{anchor=await get(resolve(mu,marker.anchor_path));}catch(e){error=e.message;}found.push({marker,anchor,error,url:mu,site,place});}}}hostedMarkers=found;return found;}
const distance=(a,b,c,d)=>{const r=6371000,x=(c-a)*Math.PI/180,y=(d-b)*Math.PI/180,h=Math.sin(x/2)**2+Math.cos(a*Math.PI/180)*Math.cos(c*Math.PI/180)*Math.sin(y/2)**2;return 2*r*Math.atan2(Math.sqrt(h),Math.sqrt(1-h));};
export async function hostedGps(){try{const items=await collectMarkers();app.innerHTML=`<div class="screen"><div class="page-header"><button class="ghost" onclick="window.openHostedProject('${projectUrl}')">Back</button><h1>${project.name}</h1><p class="subtitle">Hosted GPS markers</p></div><div class="panel"><select id="hostRadius" onchange="window.hostedGps()"><option>10</option><option>25</option><option>50</option><option selected>100</option><option>250</option><option>500</option></select><p id="hostGpsStatus">Requesting location…</p></div><div id="hostGpsResults"></div></div>`;navigator.geolocation.getCurrentPosition(pos=>{const radius=Number(document.getElementById('hostRadius').value);const near=items.filter(x=>x.anchor?.type==='gps'&&Number.isFinite(Number(x.anchor.latitude))&&Number.isFinite(Number(x.anchor.longitude))).map(x=>({...x,d:distance(pos.coords.latitude,pos.coords.longitude,Number(x.anchor.latitude),Number(x.anchor.longitude))})).filter(x=>x.d<=radius).sort((a,b)=>a.d-b.d);document.getElementById('hostGpsStatus').textContent=`Accuracy: ${Math.round(pos.coords.accuracy)} m`;document.getElementById('hostGpsResults').innerHTML=near.length?near.map(x=>`<div class="panel"><div class="list-item"><div><strong>${x.marker.name}</strong><p>${Math.round(x.d)} m · ${x.place.name}</p></div><button onclick="window.openHostedMarker('${x.url}')">Open</button></div></div>`).join(''):'<div class="panel"><p>No nearby markers.</p></div>';},e=>document.getElementById('hostGpsStatus').textContent=e.code===1?'Location permission denied.':'GPS unavailable.');}catch(e){fail(e);}}
export async function startHostedAr(url){const cached=hostedMarkers.find(x=>x.url===url);if(cached)return startArNote(cached.marker,cached.profile);await openHostedMarker(url);}
