import { BUILD_INFO } from '../services/buildInfo.js';
import { html, productHeader, bindProductHeader } from '../services/productExperience.js';
export function renderLaunchScreen(app) {
 let last=null;try{last=JSON.parse(globalThis.localStorage?.getItem('nxr-v2-last-place') || 'null');}catch{}
 app.innerHTML=`<div class="screen v2-screen v2-welcome">${productHeader('Plant literacy · spatial learning')}
 <section class="v2-hero"><div><p class="v2-eyebrow">Knowledge grows here</p><h1>A living world.<br>A closer look.</h1><p class="v2-lead">Discover the plants, people and relationships that make a place. Learn in a food forest, or explore from wherever you are.</p><div class="v2-actions"><button class="v2-primary" onclick="window.renderV1Explorer()">Explore a place →</button><button class="v2-secondary" onclick="window.renderDemoProjects()">Create &amp; manage</button></div>${last?.id?`<button class="v2-secondary" data-resume-place>Continue exploring ${html(last.name)}</button>`:''}<p class="v2-reading-label">Start with the field guide. Bring knowledge into the landscape with AR.</p></div><figure class="v2-living-wheel" data-nl-hero><div data-canvas tabindex="0" role="group" aria-label="Interactive botanical sculpture" aria-describedby="nl-instructions"><img src="assets/living-wheel.png" alt="A living circle of foliage, roots and fruit" width="1024" height="1024"></div><figcaption id="nl-instructions">Drag to explore · Arrow keys to turn.</figcaption><span class="wheel-status" data-status role="status"></span></figure></section>
 <section class="v2-intro-grid" aria-label="Ways to explore"><article><small>01 · FIND YOUR PLACE</small><h2>Follow your curiosity</h2><p>Visit a garden or food forest. Meet the plants that grow there.</p></article><article><small>02 · LOOK CLOSER</small><h2>Knowledge, connected</h2><p>Follow a plant’s uses, growing needs and relationships. See where each idea comes from.</p></article><article><small>03 · LEARN IN PLACE</small><h2>Step into the landscape</h2><p>Read on screen or try a spatial experience on a compatible device.</p><button class="v2-secondary" onclick="window.openTemporaryArDemoWindow()">Try the AR introduction</button></article></section>
 <footer class="v2-context"><button onclick="window.renderPlatformComingSoon('About This Tool','launch')">About Nourishland XR</button><span class="welcome-version-badge" aria-label="Version and release channel">V${BUILD_INFO.version} · ${BUILD_INFO.target==='production'?'Live':'Local preview'}</span></footer></div>`;
 if(app.querySelector){const wheel=app.querySelector('[data-nl-hero]');if(wheel)import('../services/landingWheel.js').then(m=>m.mountLandingWheel(wheel)).catch(()=>{});bindProductHeader(app);app.querySelector('[data-resume-place]')?.addEventListener('click',()=>window.openVisitor('place',last.id));}
}
