import { enrichTrialNodes, MORINGA_TRIAL } from '../../services/plantTrialContent.js';
import { resolvePlantPim } from '../../services/pimLegacyAdapter.js';
import { pimToArKnowledge } from '../../services/pimModel.js';
import { attachPimCellIllustrations } from '../../services/pimCellIllustrations.js';

export const MORINGA_PROFILE_IMAGE = new URL('../../assets/moringa-oleifera.jpg', import.meta.url).href;

export const MORINGA_PROFILE = Object.freeze({
    common_name: 'Moringa Tree',
    scientific_name: 'Moringa oleifera',
    pim: Object.freeze({
        schemaVersion: 1,
        plantId: 'moringa-oleifera',
        identity: Object.freeze({
            commonName: 'Moringa Tree',
            scientificName: 'Moringa oleifera',
            identityStatement: 'A fast-growing food and support tree for tropical and subtropical gardens.',
            image: MORINGA_PROFILE_IMAGE
        }),
        sources: MORINGA_TRIAL.sources,
        nodes: Object.freeze(enrichTrialNodes([
            { id: 'moringa-forest-layer', parentId: 'food-forest', title: 'Canopy / low tree layer', preview: 'Light canopy role', body: 'A fast-growing low tree within a layered food forest.', informationType: 'fact', evidenceStatus: 'needs_review', status: 'published' },
            { id: 'moringa-canopy-management', parentId: 'moringa-forest-layer', title: 'Canopy management', preview: 'Prune for light and access', body: 'Regular pruning can keep the canopy low enough for harvest while allowing useful light to reach plants below. Observe regrowth and adjust the cutting cycle to the season and the needs of neighbouring plants.', informationType: 'guidance', evidenceStatus: 'needs_review', status: 'published' },
            { id: 'moringa-layer-observation', parentId: 'moringa-forest-layer', title: 'Layer observation', preview: 'Watch shade through the year', body: 'Record where shade falls in different seasons and times of day. This makes the tree layer a local observation rather than a fixed label.', informationType: 'local_observation', evidenceStatus: 'local_observation', status: 'published' },
            { id: 'moringa-relationships', parentId: 'food-forest', title: 'Garden relationships', preview: 'Shade and mulch', body: 'Light shade and pruned biomass can support nearby garden plants.', informationType: 'guidance', evidenceStatus: 'needs_review', status: 'published' },
            { id: 'moringa-biomass-cycle', parentId: 'moringa-relationships', title: 'Biomass cycle', preview: 'Return suitable prunings', body: 'Clean leaves and soft stems can be cut into manageable pieces and used as surface mulch. Keep material clear of vulnerable stems and exclude diseased material.', informationType: 'practice', evidenceStatus: 'needs_review', status: 'published' },
            { id: 'moringa-pollinator-observation', parentId: 'moringa-relationships', title: 'Flower visitors', preview: 'Observe insects at flowers', body: 'When the tree flowers, record which insects visit, the time of day and whether nearby plants are flowering too. This creates a place-based relationship record.', informationType: 'local_observation', evidenceStatus: 'local_observation', status: 'published' },
            { id: 'moringa-culinary', parentId: 'uses', title: 'Culinary', preview: 'Leaves and pods', body: 'Nutritious leaves and long seed pods are used as food.', informationType: 'practice', evidenceStatus: 'needs_review', status: 'published' },
            { id: 'moringa-leaf-harvest', parentId: 'moringa-culinary', title: 'Leaf harvest', preview: 'Pick clean young leaflets', body: 'Harvest clean foliage from correctly identified plants and use preparation methods appropriate to the dish and local food practice. Leave enough healthy canopy for continued growth.', informationType: 'practice', evidenceStatus: 'needs_review', safetyNote: 'Confirm plant identity and use an appropriate food preparation method.', status: 'published' },
            { id: 'moringa-pod-harvest', parentId: 'moringa-culinary', title: 'Pod harvest', preview: 'Tender and mature stages differ', body: 'Tender pods and mature seed are distinct harvest stages with different textures and preparation needs. Record the stage rather than treating every pod as the same food.', informationType: 'guidance', evidenceStatus: 'needs_review', safetyNote: 'Use a preparation method suitable for the harvested stage.', status: 'published' },
            { id: 'moringa-food-context', parentId: 'moringa-culinary', title: 'Food context', preview: 'Retain recipe and source', body: 'A useful food record includes the part used, harvest stage, preparation method, recipe tradition and the person or source that supplied the knowledge.', informationType: 'traditional_knowledge', evidenceStatus: 'community_contributed', attribution: 'A named recipe source, knowledge holder or community should accompany a specific food practice.', safetyNote: 'Traditional food records do not replace allergy or dietary advice.', status: 'published' },
            { id: 'medicinal', parentId: 'uses', title: 'Medicinal', preview: 'Attributed traditions', body: 'Traditional uses must record their source and cultural context.', informationType: 'traditional_knowledge', evidenceStatus: 'needs_review', safetyNote: 'Traditional knowledge only; not medical advice.', status: 'published' },
            { id: 'moringa-medicinal-boundary', parentId: 'medicinal', title: 'Knowledge boundary', preview: 'Attribute and limit claims', body: 'Record who shared a practice, where it belongs, which plant part was discussed and any limits on sharing. Do not convert a cultural record into a universal health claim.', informationType: 'traditional_knowledge', evidenceStatus: 'community_contributed', attribution: 'A named knowledge holder or community is required for a specific traditional-use record.', safetyNote: 'This is not medical advice. Seek qualified health guidance where needed.', status: 'published' },
            { id: 'craft', parentId: 'uses', title: 'Craft', preview: 'Dry stems', body: 'Dry stems and other garden material can be used in simple crafts.', informationType: 'practice', evidenceStatus: 'needs_review', status: 'published' },
            { id: 'moringa-garden-materials', parentId: 'craft', title: 'Garden materials', preview: 'Use dry pruned stems', body: 'Dry straight stems can be trialled as lightweight garden markers, temporary supports or learning materials. Their durability depends on stem age, preparation and exposure.', informationType: 'practice', evidenceStatus: 'needs_review', status: 'published' },
            { id: 'moringa-seed', parentId: 'propagation', title: 'Seed', preview: 'Direct sowing', body: 'Seed and direct sowing are common starting methods.', informationType: 'guidance', evidenceStatus: 'needs_review', status: 'published' },
            { id: 'moringa-seed-selection', parentId: 'moringa-seed', title: 'Seed selection', preview: 'Choose mature labelled seed', body: 'Select mature seed from healthy pods and retain the source, harvest date and parent-plant notes. Labelling lets later growers compare germination and local performance.', informationType: 'practice', evidenceStatus: 'needs_review', status: 'published' },
            { id: 'moringa-germination', parentId: 'moringa-seed', title: 'Germination', preview: 'Warmth with careful moisture', body: 'Use warm conditions and a free-draining medium. Keep the medium suitably moist without prolonged saturation, and record emergence time instead of assuming every seed lot behaves alike.', informationType: 'guidance', evidenceStatus: 'needs_review', climateContext: 'Temperature and moisture affect emergence.', status: 'published' },
            { id: 'moringa-cuttings', parentId: 'propagation', title: 'Cuttings', preview: 'Vegetative start', body: 'Cuttings are another propagation pathway.', informationType: 'guidance', evidenceStatus: 'needs_review', status: 'published' },
            { id: 'moringa-cutting-establishment', parentId: 'moringa-cuttings', title: 'Cutting establishment', preview: 'Monitor stability and new growth', body: 'Protect a new cutting from movement while roots establish. Record new growth, water response and stability before treating it as an established tree.', informationType: 'guidance', evidenceStatus: 'needs_review', status: 'published' },
            { id: 'moringa-botanical-name', parentId: 'scientific-information', title: 'Botanical name', preview: 'Moringa oleifera', body: 'Moringa oleifera', informationType: 'fact', evidenceStatus: 'verified', status: 'published' },
            { id: 'moringa-family', parentId: 'scientific-information', title: 'Family', preview: 'Moringaceae', body: 'Moringaceae', informationType: 'fact', evidenceStatus: 'verified', status: 'published' },
            { id: 'moringa-growth-form', parentId: 'scientific-information', title: 'Growth form', preview: 'Fast-growing small tree', body: 'A fast-growing small tree.', informationType: 'fact', evidenceStatus: 'sourced', status: 'published' },
            { id: 'moringa-leaf-form', parentId: 'moringa-growth-form', title: 'Leaf form', preview: 'Compound leaves with small leaflets', body: 'The foliage is made of compound leaves carrying many small leaflets. Use several features together when identifying a plant rather than relying on leaves alone.', informationType: 'fact', evidenceStatus: 'needs_review', status: 'published' },
            { id: 'moringa-flowering', parentId: 'moringa-growth-form', title: 'Flowering and pods', preview: 'Flowers followed by long pods', body: 'Flowering and pod development vary with plant age, season, water and management. Dated local observations make this general pattern useful in a real place.', informationType: 'fact', evidenceStatus: 'needs_review', status: 'published' },
            { id: 'moringa-origin', parentId: 'historical-data', title: 'Origin', preview: 'South Asia', body: 'Documented origin in South Asia.', informationType: 'historical_record', evidenceStatus: 'sourced', status: 'published' },
            { id: 'moringa-origin-sources', parentId: 'moringa-origin', title: 'Origin sources', preview: 'Keep historical claims traceable', body: 'Retain the publication, date, region and wording used for an origin claim. This allows later reviewers to distinguish evidence from repeated summaries.', informationType: 'guidance', evidenceStatus: 'needs_review', status: 'published' },
            { id: 'moringa-food-cultures', parentId: 'historical-data', title: 'Food cultures', preview: 'Tropical cultivation', body: 'Cultivated through many tropical regions.', informationType: 'historical_record', evidenceStatus: 'needs_review', status: 'published' },
            { id: 'moringa-local-names', parentId: 'moringa-food-cultures', title: 'Local names and practices', preview: 'Record language and place', body: 'Record a local name with its language, place, contributor and the plant part or practice it refers to. Similar names can carry different meanings in different regions.', informationType: 'traditional_knowledge', evidenceStatus: 'community_contributed', attribution: 'A named contributor or community should accompany each local record.', status: 'published' },
            { id: 'moringa-climate', parentId: 'cultivation', title: 'Climate', preview: 'Tropical and subtropical', body: 'Adapted to tropical and subtropical growing conditions.', informationType: 'guidance', evidenceStatus: 'needs_review', status: 'published' },
            { id: 'moringa-seasonal-response', parentId: 'moringa-climate', title: 'Seasonal response', preview: 'Observe heat, rain and cool periods', body: 'Track leaf growth, flowering, pod set and stress through local wet, dry, hot and cool periods. The record is more useful than a climate label alone.', informationType: 'local_observation', evidenceStatus: 'local_observation', status: 'published' },
            { id: 'moringa-care', parentId: 'cultivation', title: 'Growing care', preview: 'Sun, drainage, pruning', body: 'Grow in full sun and free-draining soil, with regular pruning where appropriate.', informationType: 'guidance', evidenceStatus: 'needs_review', status: 'published' },
            { id: 'moringa-soil-drainage', parentId: 'moringa-care', title: 'Soil and drainage', preview: 'Avoid prolonged saturation', body: 'Establishment is generally more reliable where excess water can drain. Observe the actual soil after heavy rain before deciding how often to water.', informationType: 'guidance', evidenceStatus: 'needs_review', status: 'published' },
            { id: 'moringa-establishment-water', parentId: 'moringa-care', title: 'Establishment water', preview: 'Support roots, then reassess', body: 'Provide appropriate moisture while roots establish, then adjust watering to rainfall, soil drainage, season and the condition of the plant.', informationType: 'guidance', evidenceStatus: 'needs_review', status: 'published' },
            { id: 'moringa-pruning-cycle', parentId: 'moringa-care', title: 'Pruning cycle', preview: 'Height, harvest and regrowth', body: 'Pruning can keep foliage reachable and produce mulch material. Record the cut date, severity and regrowth response so the cycle can be adapted rather than repeated blindly.', informationType: 'practice', evidenceStatus: 'needs_review', status: 'published' },
            { id: 'moringa-health-observation', parentId: 'moringa-care', title: 'Plant health observation', preview: 'Notice change before treatment', body: 'Record where symptoms occur, when they began, recent weather, watering and management changes before choosing a response. Photographs over time can help distinguish damage from normal seasonal change.', informationType: 'local_observation', evidenceStatus: 'local_observation', status: 'published' }
        ], MORINGA_TRIAL, 'moringa-agroforestry'))
    })
});

export const MORINGA_PIM = Object.freeze(attachPimCellIllustrations(resolvePlantPim(MORINGA_PROFILE, {
    id: 'moringa-oleifera',
    plantId: 'moringa-oleifera',
    name: 'Moringa Tree',
    commonName: 'Moringa Tree',
    title: 'Moringa Tree',
    scientificName: 'Moringa oleifera'
}), 'moringa'));

export const MORINGA_KNOWLEDGE = Object.freeze(pimToArKnowledge(MORINGA_PIM));
