// Guided narration only. Placement, selection, grabbing and face activation
// continue to use the existing interaction paths.
export const DEMO_GUIDED_STEPS = Object.freeze([
    {id:'INTRO 1.1',act:'Introduce the tool',title:'Information where you need it',main:'NourishlandXR connects information to objects and locations. Open a plant profile, read a local message or follow directions. It helps you understand what is there and find what you need.',panel:'Hidden.',hint:'See how it works.',art:'opening'},
    {id:'INTRO 1.2',act:'Introduce the tool',title:'Try the tools with sample content',main:'Visitors explore. Teachers support learning. Creators organise local knowledge. This demo uses prepared examples in the room around you. No garden or plant knowledge is needed.',panel:'Hidden. A real garden project is a separate experience after the sample demo.',hint:'Start the sample demo.',art:'opening'},
    {id:'SPACE 1.1',act:'Meet the panel',title:'Your Control panel',main:'This panel shows details about what you select. The main screen gives you one next action. We will introduce the other buttons when they become useful.',panel:'A compact panel with its companion image visible. Media, Controls and Settings are initially closed.',hint:'Continue to the first sample.',art:null},
    {id:'SPACE 1.2',act:'Place a sample',title:'What is a Plant Orb?',main:'A Plant Orb is a marker that opens a plant profile. Our sample is Pigeon Pea, a shrub grown for edible peas. We chose it to demonstrate several kinds of information.',panel:'Keep the companion image available without repeating the main message.',hint:'Place the sample marker in front of you.',art:'curiosity'},
    {id:'ELEMENTS 1.5',act:'Place a sample',title:'Place the sample Orb',main:'Place the Pigeon Pea marker in a comfortable spot in front of you. This prepared profile lets you try the tool without a real plant nearby.',panel:'Existing placement controls; media closed.',hint:'Aim at an open space and use the placement control.',art:null},
    {id:'ELEMENTS 1.6',act:'Open a profile',title:'Open your first plant profile',main:'The Orb is ready. Select it to open Pigeon Pea information. Its location stays in view while you read.',panel:'Selected plant identity. Curiosity is the standard presentation.',hint:'Select the Pigeon Pea Orb.',art:null},
    {id:'ELEMENTS 1.7',act:'Open a profile',title:'The compact Tag view',main:'Tag shows the essentials. Use Controls to return to Curiosity when you want the information cells, or continue the demo.',panel:'Optional compact view, not a required lesson.',hint:'Curiosity is the standard view.',art:null},
    {id:'PIMO 1.2',act:'Find a useful detail',title:'Find a use for the sample plant',main:'Open Uses to see what this sample plant provides. We will follow one example, then show how the panel helps you read it.',panel:'Plant profile in Curiosity; keep only the relevant branch in focus.',hint:'Select Uses.',art:null},
    {id:'PIMO 1.2a',act:'Find a useful detail',title:'Choose the food examples',main:'Uses contains several kinds of information. Culinary groups the food examples. Select it to see the next choices.',panel:'Uses information and its immediate child cells.',hint:'Select Culinary.',art:null},
    {id:'PIMO 1.2b',act:'Find a useful detail',title:'Open one specific example',main:'Fresh peas describes one harvest and preparation example. Select it to read the detail.',panel:'Culinary information and its child cells.',hint:'Select Fresh peas.',art:null},
    {id:'PIMO 1.2c',act:'Find a useful detail',title:'A useful detail, ready to read',main:'Pigeon Pea\u2019s green seeds can be harvested and cooked while tender. You have moved from a plant marker to one specific piece of information.',panel:'Authored Fresh peas information, breadcrumb and matching media if available.',hint:'Continue to learn about Media.',art:null},
    {id:'PANEL 1.1',act:'Meet the panel tools',title:'Media opens the related image',main:'Media shows an image related to your selection. Open it to see the matching image. Press Media again to close it when you want more room to read.',panel:'Media is a panel opener, visually distinct from demo progression actions. Use the selected cell or plant\u2019s authored image.',hint:'Open Media, then continue.',art:null},
    {id:'PANEL 1.2',act:'Meet the panel tools',title:'Controls and Settings',main:'Controls opens view options: Curiosity is standard, Tag is compact, and Explorer is experimental. Settings opens display and comfort preferences. You can use either when needed.',panel:'Keep all mode choices visible. Controls and Settings are distinct panel toggles. Continuing restores Curiosity.',hint:'Continue in Curiosity. Trying other views is optional.',art:null},
    {id:'ELEMENTS 1.9',act:'Compare profiles',title:'Each Orb carries its own profile',main:'Add our second sample, Moringa, to see how separate markers open separate profiles. Place it beside Pigeon Pea with enough room to select either one.',panel:'Keep the first sample and its information available.',hint:'Add the Moringa sample.',art:null},
    {id:'ELEMENTS 1.11',act:'Compare profiles',title:'Place the second sample',main:'Each Orb carries its own profile. Place our second sample, Moringa, beside Pigeon Pea to see how selecting another marker changes the information.',panel:'Existing placement controls; media closed.',hint:'Place the Moringa Orb.',art:null},
    {id:'ELEMENTS 1.12',act:'Compare profiles',title:'Switch between the sample profiles',main:'Select Moringa to see its information. The panel title and image follow your selection. Pigeon Pea keeps its own profile, ready to open again.',panel:'Selected plant information only; Curiosity remains standard.',hint:'Select Moringa, or continue to add a sample Note.',art:null},
    {id:'ELEMENTS 1.14',act:'Leave a message',title:'What does a Note do?',main:'A Note attaches a message to a location. It can explain a task or give a reminder. We will use a prepared message beside the sample plants.',panel:'No invented observation or typing task.',hint:'Add the prepared Note.',art:null},
    {id:'ELEMENTS 1.16',act:'Leave a message',title:'Place the sample Note',main:'A Note attaches a message to a location. Our prepared message invites people to open either sample profile. Place it beside the Orbs.',panel:'Existing Note placement controls. Prepared message: Two sample plant profiles are available here. Select either Orb to explore.',hint:'Choose a location and place the Note.',art:'note'},
    {id:'ELEMENTS 1.17',act:'Leave a message',title:'Read the message where it belongs',main:'Select the Note to read its message. It stays associated with this location, while each plant keeps its own profile.',panel:'Selected Note content and existing Note controls.',hint:'Select the Note, then continue to organise the area.',art:null},
    {id:'SPACE 1.4',act:'Organise an area',title:'Group the sample information',main:'An Area groups related markers and messages. We will call this sample group My area. A Totem identifies it and provides signs pointing to its contents.',panel:'Keep the sample plants and Note visible.',hint:'Show the first Totem.',art:null},
    {id:'ELEMENTS 1.18',act:'Organise an area',title:'Show the first Totem',main:'A Totem identifies an Area and helps visitors find its contents. This first one belongs to My area, with signs for the sample plants and Note.',panel:'Totem example and preloaded signage. Floor adjustment remains in Settings.',hint:'Show the My area Totem.',art:'totem'},
    {id:'ELEMENTS 1.19',act:'Organise an area',title:'Signs and visibility',main:'Signs opens or closes the Totem\u2019s signage. Fade reduces the Totem\u2019s visibility; Wake restores it. These controls let you adjust the view while the Area keeps its information.',panel:'Existing Signs and Fade/Wake controls. Signs are already visible on arrival.',hint:'Try the controls if you like, then create Second Area.',art:'totem'},
    {id:'AREA 1.2',act:'Connect areas',title:'Why add a second Area?',main:'Another Area can hold its own information. Create Second Area to see how a link provides directions between two groups. Both are prepared examples in this room.',panel:'My area and its content remain visible.',hint:'Create the Second Area Totem.',art:null},
    {id:'ELEMENTS 1.20',act:'Connect areas',title:'Connect the two Totems',main:'Second Area contains its own sample plants and Note. Connect the Totems to give visitors directions between the Areas. Each keeps its own information.',panel:'Second Area and local content. No remote destination sign until the link is created.',hint:'Select Connect the Totems.',art:null},
    {id:'ELEMENTS 1.21',act:'Connect areas',title:'See which destination a sign means',main:'Select the Second Area sign on the first Totem. The destination\u2019s notification light pulses while its sign is selected, showing which Area it refers to.',panel:'Remote Totem notification uses its existing white strip. No surrounding destination outline.',hint:'Select the Second Area sign.',art:null},
    {id:'ELEMENTS 1.22',act:'Connect areas',title:'From local information to directions',main:'The same signs can point to plants, Notes or another Area. You have seen how separate groups stay organised while visitors find their way between them.',panel:'Keep local information available without repeating the full main message.',hint:'Continue to the final feature: Learning Pathways.',art:'connectedAreas'},
    {id:'LEARNING 1.6',act:'Learning pathways',title:'Turn information into a learning activity',main:'Learning Pathways connects information with questions and activities. We will use the plant detail you already opened for one prepared example.',panel:'Four uniform starting cells grow from the Living Frame. Learning Pathways is the final feature.',hint:'Open the learning example.',art:'connection'},
    {id:'LEARNING 1.7',act:'Learning pathways',title:'Four starting topics',main:'Hold a starting cell to explore its learning topic, or continue to our prepared Uses connection. Its source and target will appear together for you.',panel:'Selected learning cell information and authored image. No need to find a nested target before starting the guided connection.',hint:'Try a starting topic, or connect the sample plant.',art:'pathways'},
    {id:'LEARNING 1.8',act:'Learning pathways',title:'Use what you already opened',main:'Connect Pigeon Pea Uses to Uses and Making. This turns a plant detail into a starting point for a learning activity.',panel:'Uses is the guided default. Other prepared connection examples remain optional.',hint:'Show the source and target together.',art:null},
    {id:'CLOSURE 1.1',act:'Finish the sample',title:'You have tried the tools',main:'You opened profiles, read a local message, connected Areas and linked information to learning. These were prepared samples. After finishing, explore a separate real garden project from the welcome screen.',panel:'Finish the sample cleanly. Any available published project is a separate choice after returning to welcome.',hint:'Finish the sample demo.',art:null}
]);

export const DEMO_GUIDED_COPY = Object.freeze(Object.fromEntries(DEMO_GUIDED_STEPS.map(step=>[step.id,step.main])));
export const guidedDemoStep = id => DEMO_GUIDED_STEPS.find(step=>step.id===id);
