// Guided narration only. Placement, selection, grabbing and face activation
// continue to use the existing interaction paths.
export const DEMO_GUIDED_STEPS = Object.freeze([
    {id:'INTRO 1.1',act:'Arrive',title:'Welcome to NourishlandXR',main:'Welcome to NourishlandXR — where extended reality brings plant stories and knowledge into living landscapes.',panel:'Hidden.',hint:'Enjoy the opening.',art:'opening'},
    {id:'INTRO 1.2',act:'Arrive',title:'Extended reality, rooted in place',main:'Extended reality connects digital information with the world around you. Here, plants and places become starting points for discovery and learning.',panel:'Hidden.',hint:'Continue when you are ready.',art:'opening'},
    {id:'SPACE 1.1',act:'Arrive',title:'Meet your Control panel',main:'This is your Control Panel. Information and actions will appear here as you explore.',panel:'A compact panel with its companion image visible.',hint:'Continue when you are ready.',art:null},
    {id:'SPACE 1.2',act:'Arrive',title:'Enter the garden',main:'You arrive in a garden. A plant catches your attention — what is it, and what role does it play here?',panel:'No additional tutorial paragraph.',hint:'Add your first Plant Orb.',art:'curiosity'},
    {id:'ELEMENTS 1.5',act:'Meet a plant',title:'Place Pigeon Pea',main:'Let’s add our first Plant Orb. Pigeon Pea will be our first example.',panel:'Placement controls; media closed. Creator mode offers thousands of plants or your own profile.',hint:'Aim at an open space and press the trigger to place it.',art:null},
    {id:'ELEMENTS 1.6',act:'Meet a plant',title:'Your Plant Orb',main:'This is a Plant Orb. It connects a plant’s knowledge to this place.',panel:'No repeated placement lesson.',hint:'Select the Pigeon Pea Orb.',art:null},
    {id:'ELEMENTS 1.7',act:'Discover PIMO',title:'What is this?',main:'Meet Pigeon Pea. Its Tag brings the essentials into view.',panel:'Selected Pigeon Pea identity and essential information.',hint:'Read the Tag, then choose Curiosity.',art:null},
    {id:'PIMO 1.2',act:'Discover PIMO',title:'Follow your curiosity',main:'Curious? Explore what makes Pigeon Pea interesting. Follow a relationship or two, and notice how its knowledge connects.',panel:'Information for the selected cell; six original primary cells, with local outward expansion.',hint:'Select a cell to follow its relationships.',art:null},
    {id:'PIMO 1.3',act:'Discover PIMO',title:'Knowledge has different sides',main:'Hold the clear knowledge die and turn it to discover another side. Follow one connection, then move the child die to see how the ideas stay linked.',panel:'Selected face information. Available only in a qualified spatial session.',hint:'Touch a face and hold briefly to explore it.',art:null,spatialOnly:true},
    {id:'ELEMENTS 1.9',act:'Return to the garden',title:'Look at the garden again',main:'Which of these characteristics could matter in this garden? Take another look at the place around you.',panel:'Keep the selected plant information available.',hint:'Look around, then add Moringa.',art:null},
    {id:'ELEMENTS 1.11',act:'Add another plant',title:'Place Moringa',main:'Let’s add another plant. Consider the different roles these two plants might play here.',panel:'Placement controls; media closed.',hint:'Place Moringa beside Pigeon Pea.',art:null},
    {id:'ELEMENTS 1.12',act:'Add another plant',title:'Two plants in one place',main:'Both plant profiles are now connected to this place. Select Moringa to discover its roles, or continue when you are ready.',panel:'Moringa information appears when selected; Pigeon Pea remains available.',hint:'Select Moringa, or continue to observe the garden.',art:null},
    {id:'ELEMENTS 1.14',act:'Observe',title:'What do you notice?',main:'What do you notice in the actual landscape?',panel:'No additional tutorial paragraph.',hint:'Look around, then leave a Note.',art:null},
    {id:'ELEMENTS 1.16',act:'Observe',title:'Leave a Note',main:'Create a Note to record an observation.',panel:'Note placement controls.',hint:'Choose a location and place the Note.',art:'note'},
    {id:'ELEMENTS 1.17',act:'Observe',title:'Your Note belongs here',main:'Your Note now belongs to this location. It can hold an observation, memory or task. Select it to see a prepared example.',panel:'Selected Note content and existing Note options.',hint:'Select the Note to see the example.',art:null},
    {id:'SPACE 1.4',act:'Expand into the place',title:'One part of a larger place',main:'These plants and observations belong to one part of a larger place. An Area keeps nearby plants, Notes and guidance together.',panel:'Selected local information remains available.',hint:'Continue to meet the Area’s Totem.',art:null},
    {id:'ELEMENTS 1.18',act:'Expand into the place',title:'Meet the Totem',main:'A Totem helps identify an Area and point towards what lies beyond it.',panel:'Selected Totem information; floor adjustment remains in Settings.',hint:'Show the Totem.',art:'totem'},
    {id:'ELEMENTS 1.19',act:'Expand into the place',title:'My area',main:'This first Totem identifies My area. Its signs point towards the plants and Note you placed.',panel:'Existing signs and destination controls.',hint:'Select Show Signs to see nearby destinations.',art:'totem'},
    {id:'AREA 1.2',act:'Expand into the place',title:'A second Totem',main:'A second Totem can identify a different Area. Connecting the two Areas gives visitors a route and guidance between them.',panel:'The first Totem and its local plants and Note remain available.',hint:'Create the second Totem when you are ready.',art:null},
    {id:'ELEMENTS 1.20',act:'Expand into the place',title:'A neighbouring Area',main:'This neighbouring Area is a prepared example with its own plants and Note. The living map can extend beyond this garden section.',panel:'Second Area Totem and local content.',hint:'Connect the two Areas.',art:null},
    {id:'ELEMENTS 1.21',act:'Expand into the place',title:'The Areas are connected',main:'A route connects the two Areas. Each keeps its own plants and Notes.',panel:'Selected destination and route information.',hint:'Select a destination sign to follow its direction.',art:null},
    {id:'ELEMENTS 1.22',act:'Expand into the place',title:'A connected landscape',main:'Linked Areas can form a garden tour, learning trail or route through a working landscape.',panel:'Local information remains available.',hint:'Continue when you are ready.',art:'connectedAreas'},
    {id:'LEARNING 1.6',act:'Learning pathways',title:'Learn with the living place',main:'Learning pathways are the final feature. They connect what you discovered here with questions, relationships and practical actions, in AR or as a standalone experience.',panel:'The four pathway archetypes grow from the Living Frame.',hint:'Show the learning pathways.',art:'connection'},
    {id:'LEARNING 1.7',act:'Learning pathways',title:'Choose a learning pathway',main:'Choose one of four pathways. Its coloured outline grows from the Living Frame, with small leaves and roots developing inside. Open a pathway to follow its connected learning cells.',panel:'Information for the selected learning cell.',hint:'Select a pathway to explore.',art:'pathways'},
    {id:'CLOSURE 1.1',act:'Closure',title:'One plant can be a beginning',main:'You started with a single plant. From it, you discovered relationships, added another plant and placed a Note for an observation. As more knowledge is connected, NourishlandXR can grow with the landscape around it.',panel:'Continue building in Creator mode, or explore a published project from a standard browser.',hint:'Finish the demo when you are ready.',art:null}
]);

export const DEMO_GUIDED_COPY = Object.freeze(Object.fromEntries(DEMO_GUIDED_STEPS.map(step=>[step.id,step.main])));
export const guidedDemoStep = id => DEMO_GUIDED_STEPS.find(step=>step.id===id);
